const articles = [
  {
    id: "tsem-tower-semiconductor",
    title: "TSEM 美股档案｜Tower Semiconductor",
    date: "2026-06-15",
    category: "美股",
    subcategory: "美股档案",
    tags: ["个股:TSEM", "产业:光互联", "产业:SiPho", "产业:代工", "策略:美股档案", "AI工厂", "二阶扩散"],
    pinned: false,
    summary: "Tower Semiconductor：特色晶圆代工厂，核心不是先进制程而是SiPho/SiGe特色工艺。市场交易的真正主线是AI数据中心光互联带来的SiPho产能价值重估。13亿美元2027合同+2.9亿预付款验证客户锁产能强度。当前$262已接近Bull情景，逻辑很硬估值不便宜。",
    keywords: "TSEM Tower Semiconductor SiPho 硅光 特色代工 AI光互联 光通信 foundry",
    file: "/articles/tsem-tower-semiconductor/"
  },
  {
    id: "btc-cycle-analysis-2026",
    title: "BTC行情推演：12.6万是否已是本轮顶部？",
    date: "2026-06-15",
    category: "产业思考",
    subcategory: "加密",
    tags: ["产业:加密", "产业:BTC", "策略:周期", "宏观:减半", "宏观:ETF", "个股:MSTR", "宏观:流动性", "宏观:中期选举"],
    pinned: false,
    summary: "如果2025年10月的$126K已是本轮顶部，熊市低点大概率在2026Q4的$45K-55K。历史规律减半后18个月见顶。最大变量：ETF、Strategy增持、美联储流动性和2026年中期选举的周期共振。",
    keywords: "BTC 比特币 减半周期 微策略 Strategy ETF 中期选举 流动性 数字黄金",
    file: "/articles/btc-cycle-analysis-2026/"
  },
  {
    id: "supply-demand-storage-vs-mlcc-v3",
    title: "存储 vs MLCC 供需失衡终版对比（v3.0，含大摩06012纪要重估）",
    date: "2026-06-15",
    category: "产业思考",
    subcategory: "研报分析",
    tags: ["研报:大摩", "产业:存储", "产业:MLCC", "产业:DRAM", "产业:HBM", "产业:NAND", "产业:钽电容", "供需失衡"],
    pinned: false,
    summary: "供需失衡投资模型v3.0：存储8.55逼近S级（LTA锁价+AI推理成本托底），MLCC高端7.20回落（村田主动按住高阶价格）。差距由1.10拉大到1.35。核心启示：进攻性话语权vs防御性话语权。",
    keywords: "存储 MLCC 供需失衡 摩根士丹利 LTA 村田 海力士 三星 HBM DRAM NAND",
    file: "/articles/supply-demand-storage-vs-mlcc-v3/"
  },
  {
    id: "nasdaq100-june-2026-rebalance",
    title: "纳指100六月调整：AI基础设施与商业航天被正式纳入主流指数视野",
    date: "2026-06-15",
    category: "美股",
    subcategory: "新进指数",
    tags: ["策略:指数", "策略:纳指100", "个股:CRWV", "个股:NBIS", "个股:ALAB", "个股:RKLB", "个股:TER", "产业:AI基础设施", "产业:商业航天"],
    pinned: false,
    summary: "Nasdaq-100六月季度调整：新增CRWV/NBIS/ALAB/RKLB/TER，剔除CHTR/CTSH/INSM/VRSK/ZS。核心看点不是个股利好，而是指数层面对AI算力基础设施、AI互联、商业航天的主线确认。",
    keywords: "纳指100 Nasdaq-100 CRWV NBIS ALAB RKLB TER AI基础设施 商业航天 指数调整",
    file: "/articles/nasdaq100-june-2026-rebalance/"
  },
  {
    id: "hk-us-internet-lof-160644",
    title: "160644港美互联网LOF：AI持仓投资笔记",
    date: "2026-06-15",
    category: "A股",
    subcategory: "海外ETF配置",
    tags: ["个股:160644", "产业:AI", "策略:ETF", "策略:LOF", "港美互联网", "存储", "光通信"],
    pinned: false,
    summary: "160644已经从传统港美互联网基金变为AI硬件主线+存储周期+港美应用修复的主动型组合。前十大持仓中闪迪+美光合计16%，算力+存储合计超50%。核心看点：基金经理重押存储，不买溢价。",
    keywords: "160644 港美互联网 LOF AI硬件 存储 美光 闪迪 台积电 英伟达",
    file: "/articles/hk-us-internet-lof-160644/"
  },
  {
    id: "wf6-hbm-bottleneck",
    title: "WF6会成为HBM新的瓶颈吗？",
    date: "2026-06-14",
    category: "产业思考",
    subcategory: "存储",
    tags: ["产业:HBM", "产业:存储", "产业:WF6", "材料", "供应链", "Foosung", "瓶颈分析"],
    pinned: true,
    summary: "WF6（六氟化钨）是HBM制造必需的前驱体材料，中国钨出口管制引发供应链担忧。但WF6属于HBM产业链第四层瓶颈，远未达到HBM良率、CoWoS、GPU的战略级别。更可能复制霍尔木兹事件——先交易恐慌，然后发现库存充足。",
    keywords: "WF6 六氟化钨 HBM 存储 供应链 出口管制 Foosung 瓶颈",
    file: "/articles/wf6-hbm-bottleneck/"
  },
  {
    id: "semi-analysis-ai-gpu-scarcity",
    title: "SemiAnalysis：AI算力紧缺并未结束，2026年或再次进入供给瓶颈",
    date: "2026-06-14",
    category: "产业思考",
    subcategory: "研报分析",
    tags: ["产业:AI算力", "产业:GPU", "产业:推理", "产业:HBM", "产业:光互联", "研报:SemiAnalysis", "供给瓶颈"],
    pinned: true,
    summary: "SemiAnalysis报告：GPU租赁价格反弹40%、Blackwell交付周期拉长至6-7个月，AI算力供给过剩逻辑正在被证伪。需求从训练转向推理，HBM存储和光互联是新一轮扩张中最容易形成瓶颈的环节。",
    keywords: "SemiAnalysis GPU AI 算力 HBM 存储 光互联 推理 供给 瓶颈 NVDA MU LITE COHR",
    file: "/articles/semi-analysis-ai-gpu-scarcity/"
  },
  {
    id: "aaoi-insider-selling-analysis",
    title: "AAOI近期减持公告分析：高位集中兑现",
    date: "2026-06-12",
    category: "美股",
    subcategory: "光通信",
    tags: ["个股:AAOI", "减持", "个股分析", "光模块", "筹码"],
    pinned: true,
    summary: "AAOI 6/12集中披露5份Form 144，合计约184,053股（$3,182万），属高位集中兑现。偏利空但不是基本面爆雷，筹码利空>基本面利空。短线不建议追高，等回踩确认。",
    keywords: "AAOI 减持 Form 144 Form 4 内幕交易 光模块 筹码 高位兑现",
    file: "/articles/aaoi-insider-selling-analysis/"
  },
  {
    id: "innolight-1260h-analysis",
    title: "中际旭创被列入美国1260H清单：供应链安全被重新定价",
    date: "2026-06-12",
    category: "A股",
    subcategory: "光通信",
    tags: ["个股:中际旭创", "个股分析", "1260H", "地缘", "供应链", "出口管制"],
    pinned: true,
    summary: "中际旭创被美国列入1260H清单，光模块进入产业景气+供应链安全+地缘政治三重定价阶段。不是逻辑崩了，是定价框架变了。美股LITE/COHR/AAOI/GLW反而获得政策溢价。",
    keywords: "中际旭创 1260H 光模块 供应链 出口管制 地缘政治 LITE COHR AAOI",
    file: "/articles/innolight-1260h-analysis/"
  },
  {
    id: "aaoi-trading-note",
    title: "AAOI参与笔记：可以做，但不能当核心重仓",
    date: "2026-06-12",
    category: "美股",
    subcategory: "光通信",
    tags: ["个股:AAOI", "策略:弹性仓", "光模块", "800G", "1.6T", "订单驱动"],
    pinned: true,
    summary: "AAOI不是光模块龙头老大，是AI光互连里弹性最大、波动最大、兑现压力也最大的订单驱动型标的。适合3%-5%弹性仓，不适合核心重仓。核心验证：订单、毛利率、现金流、融资节奏。",
    keywords: "AAOI 光模块 800G 1.6T 弹性 订单 融资 风险 参与策略",
    file: "/articles/aaoi-trading-note/"
  },
  {
    id: "optical-portfolio-rebuilding",
    title: "光互连组合重建：从光模块到全链条",
    date: "2026-06-12",
    category: "产业思考",
    subcategory: "光通信",
    tags: ["产业:光通信", "策略:组合重建", "个股:LITE", "个股:COHR", "个股:CRDO", "个股:TSEM", "DSP", "硅光"],
    pinned: true,
    summary: "光互连组合核心应从光模块升级为激光器+光器件+DSP/SerDes+硅光代工+测试+光纤的全链条配置。新增标的优先级：CRDO > TSEM > VIAV > GFS > AXTI > FORM > SIVEF。",
    keywords: "光通信 光互连 LITE COHR CRDO TSEM 硅光 DSP AEC 组合 配置",
    file: "/articles/optical-portfolio-rebuilding/"
  },
  {
    id: "dongshan-intraday-t-note",
    title: "东山精密日内做T思路笔记",
    date: "2026-06-12",
    category: "A股",
    subcategory: "交易框架",
    tags: ["个股:东山精密", "策略:做T", "A股", "交易体系", "PCB", "光模块"],
    pinned: true,
    summary: "东山精密日内做T的核心框架：大盘不杀→光/PCB不弱→东山有支撑→价差够→才做T。重点不是最低点最高点，是判断波动是板块回踩还是趋势走弱。",
    keywords: "东山精密 做T 日内交易 T+1 正T 倒T 光模块 PCB AI PCB VWAP 支撑 压力",
    file: "/articles/dongshan-intraday-t-note/"
  },
  {
    id: "cpi-round-two-analysis",
    title: "这次CPI的核心问题：AI牛市会不会遇到第二轮通胀冲击",
    date: "2026-06-11",
    category: "近期热点",
    subcategory: "宏观",
    tags: ["宏观:CPI", "宏观:通胀", "宏观:FOMC", "宏观分析", "AI", "市场分析"],
    pinned: true,
    summary: "结合上周五QQQ-5%大跌看CPI：核心环比0.2%说明通胀上升主要是能源问题而非经济过热。上周五的暴跌是'预防性去风险'而非趋势反转。FOMC和日本央行是接下来两颗雷。光互联和存储仍是主线。",
    keywords: "CPI 通胀 AI FOMC 日本央行 光通信 存储 DRAM HBM 去杠杆",
    file: "/articles/cpi-round-two-analysis/"
  },
  {
    id: "oracle-fy2026-q4-earnings",
    title: "甲骨文FY26Q4财报：机构视角笔记",
    date: "2026-06-11",
    category: "美股",
    subcategory: "财报分析",
    tags: ["财报:ORCL", "财报分析", "Oracle", "AI", "云", "OCI", "CapEx"],
    pinned: true,
    summary: "Oracle Q4营收$191.84亿(+21%)，OCI +93%，RPO达$6380亿(+363%)。但CapEx暴增至$556亿，FCF转负$-237亿，市场重新定价重资产AI基建逻辑。需求端极强，财务质量有压力。",
    keywords: "Oracle ORCL 甲骨文 财报 FY2026 OCI AI 云 CapEx RPO 自由现金流",
    file: "/articles/oracle-fy2026-q4-earnings/"
  },
  {
    id: "global-ai-dc-industry-chain",
    title: "全球AI数据中心产业链国家分工深度研报",
    date: "2026-06-08",
    category: "产业思考",
    subcategory: "研报分析",
    tags: ["产业:AI数据中心", "产业:国家分工", "研报整理", "GPU", "HBM", "光模块", "电力冷却"],
    pinned: true,
    summary: "AI数据中心是一台全套协作的机器：美国定义架构，台湾制造算力，韩国提供HBM，日本和荷兰卡住设备/材料，欧洲提供电力，中国参与光模块和国产替代。利润池正从GPU单点外溢到HBM、先进封装、光互连、电力冷却。",
    keywords: "AI DC 数据中心 产业链 国家分工 TSMC NVIDIA SK Hynix ASML 光模块 电力 冷却 国产替代",
    file: "/articles/global-ai-dc-industry-chain/"
  },
  {
    id: "hbm-pricing-repricing",
    title: "HBM4重新定价：SemiAnalysis杀的是SOCAMM，不是HBM",
    date: "2026-06-08",
    category: "产业思考",
    subcategory: "研报分析",
    tags: ["产业:HBM", "产业:存储", "个股:MU", "个股:SK海力士", "NVIDIA", "Rubin", "SOCAMM"],
    pinned: true,
    summary: "SemiAnalysis砍的是CPU侧SOCAMM高配预期，不是GPU侧HBM4。Bernstein指出Vera Rubin整柜成本不是$780万而是$910万，核心差异来自HBM4价格假设（16.6→53美元/GB）。HBM正从配套成本变成决定整柜利润分配的战略资源。",
    keywords: "HBM HBM4 SOCAMM LPDDR NVIDIA Rubin Bernstein SemiAnalysis SK海力士 MU Micron 存储 DRAM",
    file: "/articles/hbm-pricing-repricing/"
  },
  {
    id: "ai-cage-connector",
    title: "Cage：AI互联升级里容易被忽略的小环节",
    date: "2026-06-04",
    category: "产业思考",
    subcategory: "光通信",
    tags: ["产业:光通信", "产业:连接器", "产业链", "散热", "二阶扩散"],
    summary: "AI集群扩大→高速接口密度提升→cage需求增加→1.6T功耗提升驱动普通cage向散热/液冷cage升级。连接器与精密结构件公司获得AI互联二阶扩散机会。",
    keywords: "cage 连接器 鼎通 奕东 光模块 铜缆 散热 液冷 AI互联 二阶扩散 结构件",
    file: "/articles/ai-cage-connector/"
  },
  {
    id: "avgo-fy2026-q2-earnings",
    title: "博通 AVGO 财报笔记：AI 需求继续上修，但股价输给了过高预期",
    date: "2026-06-04",
    category: "美股",
    subcategory: "财报分析",
    tags: ["财报:AVGO", "财报分析", "AI", "ASIC", "产业链"],
    pinned: true,
    summary: "总收入+48%、AI半导体+143%、FCF margin 46%——基本面继续强化，但2027年目标未上修导致短期交易预期降温。核心确认：AI投资正从GPU单点扩散到定制ASIC、AI网络、光互联、HBM和先进封装。",
    keywords: "AVGO 博通 财报 FY2026 AI ASIC 定制芯片 英伟达 Semiconductors Networking 产业链 光通信",
    file: "/articles/avgo-fy2026-q2-earnings/"
  },
  {
    id: "optical-communication-learning-path",
    title: "AI光通信学习路径：从信号路径到投资价值链",
    date: "2026-06-03",
    category: "产业思考",
    subcategory: "光通信",
    tags: ["产业:光通信", "产业链", "学习路径", "方法论"],
    summary: "不要从名词表硬背，按信号路径+投资价值链理解。6个核心概念搞懂光通信：EML/PD/DSP/FAU/NPO/CPO，附公司映射和投资优先级排序。",
    keywords: "光通信 学习 EML PD DSP FAU NPO CPO 800G 1.6T 硅光 OCS 投资 产业链",
    file: "/articles/optical-communication-learning-path/"
  },
  {
    id: "hormuz-strait-crisis",
    title: "霍尔木兹海峡'通行许可系统'开放：危机解除了吗？",
    date: "2026-06-02",
    category: "近期热点",
    tags: ["宏观", "地缘政治", "能源"],
    summary: "短线是缓和信号，中线是伊朗把霍尔木兹海峡制度化为地缘谈判筹码。从硬封锁转向软管制——对原油、黄金、美元、美股科技和板块分化的完整分析。",
    keywords: "霍尔木兹 伊朗 原油 地缘政治 黄金 避险 能源 LNG 中东 战争溢价 航运",
    file: "/articles/hormuz-strait-crisis/"
  },
  {
    id: "industry-glossary-2026",
    title: "AI产业术语全解：从CPO到TGV的23个核心概念",
    date: "2026-06-02",
    category: "产业思考",
    subcategory: "光通信",
    tags: ["产业:光通信", "产业链", "AI", "先进封装", "术语"],
    summary: "按'它是什么→产业链位置→投资含义'拆解CPO、NPO、PD、OCS、DSP、EML、CW Laser、FAU、TIA、Driver、SerDes、硅光、轻相干、AEC、CoWoS、TGV、Interposer、Glass Core、ABF等23个核心概念。",
    keywords: "CPO NPO PD OCS DSP EML CW Laser FAU TIA Driver SerDes 硅光 轻相干 AEC Scale-up Scale-out CoWoS TGV Interposer Glass Core ABF 光互连 先进封装",
    file: "/articles/industry-glossary-2026/"
  },
  {
    id: "investment-framework",
    title: "投资框架笔记",
    date: "2026-05-28",
    category: "产业思考",
    pinned: true,
    tags: ["框架", "A股", "美股"],
    summary: "底层信念、Follow the Money、三类钱框架、买卖点、A股轮动规律——投资的完整思维模型。",
    keywords: "投资框架 方法论 底层信念 三类资产 买卖点 轮动 Follow the Money 产业链",
    file: "/articles/investment-framework/"
  },
  {
    id: "server-bom-analysis",
    title: "AI服务器代际升级BOM分析",
    date: "2026-05-21",
    category: "美股",
    tags: ["AI", "产业链", "美股"],
    summary: "从GB300到VR200——AI服务器单柜BOM成本+95%，HBM增+435%，PCB增+233%，系统级价值量全面升级。",
    keywords: "AI服务器 BOM GB300 VR200 HBM PCB 代际升级 价值量 英伟达 NVIDIA 供应链",
    file: "/articles/server-bom-analysis/"
  },
  {
    id: "ai-nuclear-chain",
    title: "AI核电全产业链拆解",
    date: "2026-05-27",
    category: "美股",
    tags: ["AI", "产业链", "美股"],
    summary: "从铀矿到SMR到核电运营商——AI数据中心电力需求驱动核电价值重估。LEU逻辑最硬，CEG最稳，OKLO彩票最高。",
    keywords: "核电 AI电力 SMR 铀矿 LEU CEG OKLO VST 数据中心 能源",
    file: "/articles/ai-nuclear-chain/"
  },
  {
    id: "a-share-rules",
    title: "A股市场定价规则",
    date: "2026-05-25",
    category: "A股",
    tags: ["A股", "框架"],
    summary: "叙事弹性、题材节奏、估值潜规则、产业链轮动——A股21条不成文的市场定价规则。",
    keywords: "A股 规则 叙事弹性 题材 估值 游资 公募 轮动 龙一 龙二",
    file: "/articles/a-share-rules/"
  },
  {
    id: "ai-industry-profit-chain",
    title: "AI产业链收益排序分析",
    date: "2026-05-25",
    category: "产业思考",
    tags: ["AI", "产业链", "A股"],
    summary: "利润兑现、卡脖子、受益时序、A股弹性——四维度拆解AI基础设施链条的投资顺序。",
    keywords: "AI产业链 收益排序 卡脖子 GPU HBM CoWoS 光模块 电力 液冷 存储",
    file: "/articles/ai-industry-profit-chain/"
  },
  {
    id: "asia-market-correlation",
    title: "亚盘四国联动分析",
    date: "2026-05-28",
    category: "A股",
    tags: ["复盘", "A股"],
    summary: "上证 vs KOSPI vs 日经 vs 台股——85%方向同步率背后的幅度差异与A股独立性。",
    keywords: "亚盘 联动 上证 KOSPI 日经 台股 韩国 日本 台湾 A股 复盘",
    file: "/articles/asia-market-correlation/"
  },
  {
    id: "a-share-framework",
    title: "A股炒作传导逻辑框架",
    date: "2026-05-29",
    category: "A股",
    tags: ["A股", "框架"],
    summary: "龙一→龙二→细分瓶颈→低位补涨→参股蹭概念→退潮——A股题材炒作从启动到退潮的完整传导路径与判断框架。",
    keywords: "A股炒作 传导 龙一 龙二 补涨 瓶颈 参股 蹭概念 退潮 情绪 题材 轮动",
    file: "/articles/a-share-framework/"
  },
  {
    id: "a-share-optical-mapping",
    title: "AI光通信下一层瓶颈：从光模块到EML、InP与互联芯片",
    date: "2026-05-28",
    category: "A股",
    tags: ["A股", "光通信"],
    summary: "A股光通信五层映射模型——从EML/激光器到InP衬底到互联芯片到平台型到模块龙头，三种排序框架（瓶颈/确定性/弹性）。",
    keywords: "光通信 EML InP 互联芯片 源杰科技 澜起科技 中际旭创 新易盛 光模块 LITE AXTI MRVL",
    file: "/articles/a-share-optical-mapping/"
  },
  {
    id: "dongshan-clarification",
    title: "东山精密：市场传言澄清与核心基本面梳理",
    date: "2026-06-01",
    category: "A股",
    tags: ["A股", "东山精密"],
    summary: "针对网络三条谣言的逐一澄清——收购审批已全部通关、实控人正常履职、港股上市独立推进。光芯片产能22KK→28KK/月，AWS/Oracle/Meta订单落地。",
    file: "/articles/dongshan-clarification/"
  },
  {
    id: "gtc-taipei-2026",
    title: "英伟达台北 GTC 2026：AI 投资从'买 GPU'进入'建 AI 工厂'",
    date: "2026-06-01",
    category: "近期热点",
    tags: ["美股", "AI", "产业链"],
    summary: "Vera Rubin量产爬坡、Spectrum-X CPO光互联方案、AI Factory BOM价值量重估——台北GTC确认AI投资从买GPU进入建AI工厂阶段。",
    file: "/articles/gtc-taipei-2026/"
  },
  {
    id: "june-market-outlook",
    title: "六月行情展望：不是简单看多看空，而是进入'产业约束筛选月'",
    date: "2026-05-31",
    category: "近期热点",
    tags: ["美股", "A股", "AI"],
    pinned: true,
    summary: "世界杯注意力折价、巨型IPO再平衡、FOMC利率定价、AI硬件扩散——六月不是简单看多看空，而是产业约束筛选月。",
    keywords: "六月 行情 展望 世界杯 FOMC SpaceX IPO 长鑫 产业约束 光互联 HBM PCB 瓶颈",
    file: "/articles/june-market-outlook/"
  },
  {
    id: "ai-pcb-hvlp-copper-foil",
    title: "AI PCB 上游材料扩散：HVLP 铜箔正在成为新一轮瓶颈",
    date: "2026-05-31",
    category: "A股",
    tags: ["A股", "产业链"],
    summary: "AI服务器高速互联推动PCB材料体系整体升级——从HVLP4/5铜箔到电子布、硅微粉、mSAP药水，资金从PCB龙头扩散到上游瓶颈环节。",
    keywords: "PCB HVLP 铜箔 铜冠铜箔 德福科技 生益科技 CCL 电子布 硅微粉 mSAP 泰金新能 三孚新科",
    file: "/articles/ai-pcb-hvlp-copper-foil/"
  },
  {
    id: "daodejing-chapter-4",
    title: "《道德经》第四章：真正强大的，往往看不见",
    date: "2026-06-14",
    category: "学点道德经",
    tags: ["学点道德经"],
    summary: "道冲，而用之或不盈。真正强大的东西，往往并不急于证明自己强大。世界上最深的力量，往往藏在最安静的地方。",
    keywords: "道德经 第四章 道冲 冲而不盈 和光同尘 挫锐解纷 柔 留白 空间",
    file: "/articles/daodejing-chapter-4/"
  },
  {
    id: "daodejing-chapter-3",
    title: "《道德经》第三章：少一点刺激，心就不容易乱",
    date: "2026-05-31",
    category: "学点道德经",
    tags: ["学点道德经"],
    summary: "少一点外界的刺激，心就少一点混乱；多一点真实的根基，人就多一点安定。人不是靠更多刺激变清醒，而是靠减少刺激恢复清醒。",
    keywords: "道德经 第三章 欲望 刺激 比较 焦虑 投资 心态 降噪",
    file: "/articles/daodejing-chapter-3/"
  },
  {
    id: "space-sector-analysis",
    title: "SpaceX估值下修、Blue Origin事故，对太空股到底意味着什么？",
    date: "2026-05-30",
    category: "近期热点",
    tags: ["航天", "美股"],
    summary: "SpaceX估值锚从2万亿下修到1.8万亿，Blue Origin事故影响发射排期——12个Q&A拆解太空股调整的本质：从主题行情进入兑现行情。",
    keywords: "SpaceX Blue Origin ASTS RKLB 太空 航天 IPO 估值 发射 New Glenn 卫星 商业航天",
    file: "/articles/space-sector-analysis/"
  },
  {
    id: "daodejing-chapter-2",
    title: "《道德经》第二章：不要在比较里失去自己",
    date: "2026-05-29",
    category: "学点道德经",
    tags: ["学点道德经"],
    summary: "比较可以帮助我们认识差异，但执着于比较，会让人失去自己。知道世界有高下，但心不必随之倾斜。",
    keywords: "道德经 第二章 比较 无为 功成弗居 投资 心态",
    file: "/articles/daodejing-chapter-2/"
  },
  {
    id: "daodejing-chapter-1",
    title: "《道德经》第一章：不要急着给世界命名",
    date: "2026-05-29",
    category: "学点道德经",
    tags: ["学点道德经"],
    summary: "不要急着给世界命名，也不要被自己起的名字困住。世界比我们的判断更大，人生比某个阶段更长，市场也比任何一个故事更复杂。",
    keywords: "道德经 第一章 道 名 命名 投资 认知 标签 判断",
    file: "/articles/daodejing-chapter-1/"
  },
  {
    id: "eml-bottleneck",
    title: "EML涨价背后：AI光通信产业链的真实瓶颈正在上移",
    date: "2026-05-28",
    category: "产业思考",
    subcategory: "光通信",
    tags: ["产业:光通信", "产业:EML", "产业链", "AI", "涨价"],
    summary: "EML涨价、交期拉长、InP产能紧张——AI光通信瓶颈从光模块上移至光芯片，LITE/COHR最直接受益，国产替代有窗口但需验证。",
    keywords: "EML InP 光通信 激光器 LITE COHR 源杰科技 长光华芯 光模块 涨价 瓶颈 AXTI 磷化铟",
    file: "/articles/eml-bottleneck/"
  },
  {
    id: "inp-industry-chain",
    title: "InP（磷化铟）产业链全景",
    date: "2026-05-28",
    category: "产业思考",
    subcategory: "光通信",
    tags: ["产业:InP", "产业链", "AI", "材料"],
    summary: "从衬底到光模块到AI数据中心——InP是AI光通信最上游的\"卖水人\"。",
    keywords: "InP 磷化铟 衬底 光通信 EML 激光器 LITE COHR AXTI 6英寸 外延 光模块",
    file: "/articles/inp-industry-chain/"
  }
];
