// ========================================
// 逻辑验证日历 — 手动维护，按时间排序
// ========================================

const calendarEvents = [
  {
    date: "2026-06-10",
    title: "美光（MU）FY2026 Q3 财报",
    type: "财报",
    stocks: "MU / DRAM",
    importance: "高",
    note: "HBM价格趋势、1γ制程进展、数据中心收入占比",
  },
  {
    date: "2026-06-15",
    title: "OpenAI 定制芯片项目量产节点",
    type: "产能",
    stocks: "AVGO / MRVL",
    importance: "高",
    note: "AVGO电话会提及预计2026年底进入量产",
  },
  {
    date: "2026-06-中旬",
    title: "ASTS 卫星发射窗口",
    type: "产品",
    stocks: "ASTS",
    importance: "中高",
    note: "下次发射进度直接决定覆盖时间表",
  },
  {
    date: "2026-06-25",
    title: "NVIDIA GTC 中国站",
    type: "会议",
    stocks: "NVDA / LITE / COHR / AAOI",
    importance: "高",
    note: "CPO量产进展、Spectrum-X订单、AI Factory架构",
  },
  {
    date: "2026-07-中旬",
    title: "A股光通信中报预告密集期",
    type: "财报",
    stocks: "002384.SZ / 600487.SH / 603083.SH / 300502.SZ",
    importance: "高",
    note: "验证800G出货和毛利率趋势",
  },
  {
    date: "2026-07-下旬",
    title: "RKLB 电子号发射任务",
    type: "产品",
    stocks: "RKLB",
    importance: "中",
    note: "发射节奏和Neutron进展",
  },
  {
    date: "2026-08-上旬",
    title: "LITE FY2026 Q4 财报",
    type: "财报",
    stocks: "LITE",
    importance: "高",
    note: "EML出货量、毛利率、1.6T和CPO进展",
  },
  {
    date: "2026-08-中旬",
    title: "COHR FY2026 Q4 财报",
    type: "财报",
    stocks: "COHR",
    importance: "高",
    note: "英伟达订单兑现、InP产能利用率",
  },
  {
    date: "2026-08-下旬",
    title: "MRVL FY2027 Q2 财报",
    type: "财报",
    stocks: "MRVL",
    importance: "高",
    note: "Custom XPU收入、数据中心增长、毛利率趋势",
  },
  {
    date: "2026-Q3",
    title: "AAOI 800G出货加速验证",
    type: "产能",
    stocks: "AAOI",
    importance: "高",
    note: "观察800G月产能和hyperscaler订单持续性",
  },
  {
    date: "2026-Q3",
    title: "GLW Optical Communications 增长验证",
    type: "财报",
    stocks: "GLW",
    importance: "中高",
    note: "观察光纤业务是否维持25-35%增长",
  },
  {
    date: "2026-Q3",
    title: "AXTI 6英寸InP研发进展",
    type: "产能",
    stocks: "AXTI",
    importance: "中",
    note: "6英寸InP良率和客户认证进度",
  },
  {
    date: "2026-09-中旬",
    title: "AVGO FY2026 Q3 财报",
    type: "财报",
    stocks: "AVGO",
    importance: "极高",
    note: "AI半导体增速、FY2027目标是否上修、Networking占比",
  },
  {
    date: "2026-Q4",
    title: "AI服务器供应链订单兑现验证",
    type: "订单",
    stocks: "CRWV / VRT / HPE / DELL",
    importance: "高",
    note: "GB300/VR200量产对AI基建股的拉动",
  },
  {
    date: "2026-12",
    title: "稳定币法案立法窗口",
    type: "政策",
    stocks: "CRCL / COIN",
    importance: "高",
    note: "参议院审议进展直接影响CRCL估值逻辑",
  },
  {
    date: "2027-H1",
    title: "TSEM 2027 SiPho 13亿美元合同收入确认",
    type: "订单",
    stocks: "TSEM",
    importance: "极高",
    note: "确认SiPho合同按期转收入、毛利率、产能利用率",
  },
];
