// ========================================
// 关键验证日历 — 月度聚焦
// 规则：只保留未来 30 天内有明确时间锚点、可能影响定价的关键事件
// 虚的（Q3/H1/下旬无日期、验证描述）不入库
// ========================================

const calendarEvents = [
  {
    date: "2026-06-10",
    title: "Oracle（ORCL）Q4 FY2026 财报（盘后）",
    type: "财报",
    stocks: "ORCL / AI云 / 企业IT",
    importance: "高",
    status: "等待验证",
    marketExpect: "AI云（OCI）增速为核、对标AWS/Azure，市场关注CapEx和GPU部署节奏",
    verifyPoint: "OCI收入增速、AI基础设施支出指引、Q4总营收对比预期",
    impactPath: "若OCI超预期，可能提振企业云/AI应用板块；反之加剧科技股调整",
    topPriority: false,
  },
  {
    date: "2026-06-11",
    title: "5月CPI（8:30 ET）",
    type: "宏观",
    stocks: "QQQ / 10Y / DXY / SOX",
    importance: "极高",
    status: "等待验证",
    marketExpect: "SMH -9.2%+QQQ -4.8%后市场对通胀数据极度敏感",
    verifyPoint: "核心CPI环比是否低于预期、服务通胀是否松动",
    impactPath: "低于预期→科技反弹/高于预期→二次杀估值",
    topPriority: true,
  },
  {
    date: "2026-06-12",
    title: "5月PPI",
    type: "宏观",
    stocks: "QQQ / 10Y / DXY",
    importance: "中",
    status: "等待验证",
    marketExpect: "接力CPI，确认成本端通胀路径",
    verifyPoint: "核心PPI环比、中间品价格变化",
    impactPath: "PPI+CPI组合决定FOMC前市场通胀叙事",
    topPriority: false,
  },
  {
    date: "2026-06-11",
    title: "SpaceX IPO 定价日",
    type: "IPO",
    stocks: "SPCX / RKLB / ASTS / 太空概念",
    importance: "极高",
    status: "待验证:定价",
    marketExpect: "路演6/4开始，预计6/11定价$135/股，目标估值~$1.77T，融资~$750亿，史上最大IPO",
    verifyPoint: "最终定价是否$135、发行规模、超额认购倍数、机构需求",
    impactPath: "定价结果决定上市首日走势；若大幅超募，首日可能高开；若定价偏保守，首日涨幅可观",
    topPriority: true,
  },
  {
    date: "2026-06-12",
    title: "SpaceX 上市首日（Nasdaq: SPCX）",
    type: "IPO",
    stocks: "SPCX / RKLB / ASTS / 太空概念",
    importance: "极高",
    status: "已确认",
    marketExpect: "S-1已公开（5/20），SEC文件确认Nasdaq上市，代码SPCX，固定价$135/股，估值~$1.77T（超Tesla）",
    verifyPoint: "首日开盘价、换手率、收盘涨跌幅、市值变化、是否触发S&P 500入指讨论",
    impactPath: "若首日大涨，可能带动太空板块（RKLB/ASTS）比价重估；S&P 500要求12个月 seasoning period，短期不入指",
    topPriority: true,
  },
  {
    date: "2026-06-16",
    title: "FOMC 利率决议（6月会议·含新闻发布会）",
    type: "宏观",
    stocks: "QQQ / 10Y / DXY / 所有风险资产",
    importance: "极高",
    status: "等待验证",
    marketExpect: "市场Price in维持利率不变，关注点阵图和鲍威尔讲话",
    verifyPoint: "点阵图是否暗示下半年降息路径、通胀预期是否上调、经济预测摘要",
    impactPath: "若释放降息信号，科技成长股（NVDA/AVGO/LITE/AAOI）可能反弹；若偏鹰，继续压制估值",
    topPriority: true,
  },
  {
    date: "2026-06-25",
    title: "美光（MU）FY2026 Q3 财报",
    type: "财报",
    stocks: "MU / DRAM / HBM",
    importance: "高",
    status: "等待验证",
    marketExpect: "HBM供给紧张、DRAM涨价继续传导",
    verifyPoint: "HBM收入占比是否继续提升、毛利率是否改善、数据中心需求指引是否上修",
    impactPath: "若指引上修，可能带动存储设备（AMAT/LRCX）与A股材料链扩散",
    topPriority: true,
  },
  {
    date: "2026-06-25",
    title: "NVIDIA GTC 中国站",
    type: "会议",
    stocks: "NVDA / LITE / COHR / AAOI",
    importance: "高",
    status: "等待验证",
    marketExpect: "CPO量产进展、Spectrum-X订单、AI Factory架构更新",
    verifyPoint: "CPO量产时间表是否明确、光器件供应链是否继续紧缺",
    impactPath: "若CPO路线确认加速，LITE/COHR的瓶颈溢价可能进一步提升",
    topPriority: true,
  },
  {
    date: "2026-06-中旬",
    title: "ASTS 三颗 BlueBird 卫星发射",
    type: "发射",
    stocks: "ASTS",
    importance: "高",
    status: "等待验证",
    marketExpect: "公司已确认6月中旬SpaceX Falcon 9发射窗口",
    verifyPoint: "发射是否成功、卫星部署节奏是否支持2026覆盖扩张预期",
    impactPath: "若发射成功并进入商业覆盖阶段，可能推动ASTS估值上修",
    topPriority: false,
  },
];

// 近期最重要三件事
const topThree = [
  { date: "2026-06-12", title: "SpaceX 上市首日：太空板块估值重塑", stocks: "SPCX / RKLB / ASTS" },
  { date: "2026-06-16", title: "FOMC利率决议：点阵图决定Q3方向", stocks: "QQQ / 10Y" },
  { date: "2026-06-25", title: "MU财报 + GTC中国站：AI链核心验证日", stocks: "MU / NVDA / LITE / COHR" },
];
