// ========================================
// 逻辑验证日历 — 投资假设跟踪系统
// ========================================

const calendarEvents = [
  {
    date: "2026-06-10",
    title: "美光（MU）FY2026 Q3 财报",
    type: "财报",
    stocks: "MU / DRAM / HBM",
    importance: "高",
    status: "等待验证",
    marketExpect: "HBM供给持续紧张、DRAM涨价继续传导",
    verifyPoint: "HBM收入占比是否继续提升、毛利率是否改善、数据中心需求指引是否上修",
    impactPath: "若指引上修，可能继续带动存储设备（AMAT/LRCX）与A股材料链扩散",
    topPriority: true,
  },
  {
    date: "2026-06-中旬",
    title: "OpenAI 定制芯片项目量产节点",
    type: "产能",
    stocks: "AVGO / MRVL",
    importance: "高",
    status: "等待验证",
    marketExpect: "AVGO电话会提及预计2026年底进入量产",
    verifyPoint: "量产时间表是否明确、客户订单能见度是否提升",
    impactPath: "若确认量产节奏，可能打开AVGO/MRVL定制ASIC估值空间",
    topPriority: true,
  },
  {
    date: "2026-06-中旬",
    title: "ASTS 卫星发射窗口",
    type: "发射",
    stocks: "ASTS",
    importance: "中高",
    status: "等待验证",
    marketExpect: "发射节奏直接决定覆盖时间表",
    verifyPoint: "卫星部署节奏是否支持2026-2027覆盖扩张预期",
    impactPath: "若发射成功并进入商业覆盖阶段，可能推动ASTS估值上修",
    topPriority: true,
  },
  {
    date: "2026-06-25",
    title: "NVIDIA GTC 中国站",
    type: "会议",
    stocks: "NVDA / LITE / COHR / AAOI",
    importance: "高",
    status: "等待验证",
    marketExpect: "CPO量产进展、Spectrum-X订单、AI Factory架构更新",
    verifyPoint: "CPO量产时间表是否明确、光器件供应链是否继续紧缺",
    impactPath: "若CPO路线确认加速，LITE/COHR的瓶颈溢价可能进一步提升",
    topPriority: true,
  },
  {
    date: "2026-07-中旬",
    title: "A股光通信中报预告密集期",
    type: "财报",
    stocks: "002384.SZ / 600487.SH / 603083.SH / 300502.SZ",
    importance: "高",
    status: "等待验证",
    marketExpect: "800G出货放量、光模块毛利率改善",
    verifyPoint: "800G出货是否继续放量、毛利率是否证明高端光模块不是低毛利订单",
    impactPath: "若业绩超预期，可能带动A股光通信板块第二轮上涨",
  },
  {
    date: "2026-07-下旬",
    title: "RKLB 电子号发射任务",
    type: "发射",
    stocks: "RKLB",
    importance: "中",
    status: "等待验证",
    marketExpect: "发射频率是否支持2026指引",
    verifyPoint: "发射节奏和Neutron大型火箭进展是否按计划推进",
    impactPath: "若持续高频发射，可能验证RKLB运营能力，支撑估值",
  },
  {
    date: "2026-08-上旬",
    title: "LITE FY2026 Q4 财报",
    type: "财报",
    stocks: "LITE",
    importance: "高",
    status: "等待验证",
    marketExpect: "EML出货量、毛利率维持高位、1.6T进展",
    verifyPoint: "EML出货是否持续供不应求、毛利率是否维持45%+、1.6T和CPO进展",
    impactPath: "若毛利率维持+1.6T订单明确，LITE的瓶颈资产逻辑继续强化",
  },
  {
    date: "2026-08-中旬",
    title: "COHR FY2026 Q4 财报",
    type: "财报",
    stocks: "COHR",
    importance: "高",
    status: "等待验证",
    marketExpect: "英伟达订单兑现、InP产能利用率、数据中心收入占比",
    verifyPoint: "英伟达合作是否转化为实质订单、InP产能利用率是否提升",
    impactPath: "若收入继续超预期，COHR平台型溢价可能维持或扩大",
  },
  {
    date: "2026-08-下旬",
    title: "MRVL FY2027 Q2 财报",
    type: "财报",
    stocks: "MRVL",
    importance: "高",
    status: "等待验证",
    marketExpect: "Custom XPU收入、数据中心增速、毛利率趋势",
    verifyPoint: "Custom XPU/XPU-attach收入是否开始体现、毛利率能否维持58-60%",
    impactPath: "若数据中心+Custom XPU双线超预期，MRVL估值可能继续靠近AVGO",
  },
  {
    date: "2026-Q3",
    title: "AAOI 800G出货加速验证",
    type: "产能",
    stocks: "AAOI",
    importance: "高",
    status: "等待验证",
    marketExpect: "800G月产能和hyperscaler订单持续性",
    verifyPoint: "800G出货是否环比增长、毛利率是否回升至30%+",
    impactPath: "若出货量持续放大+毛利率改善，AAOI可能从题材切向业绩驱动",
  },
  {
    date: "2026-Q3",
    title: "GLW Optical Communications 增长验证",
    type: "财报",
    stocks: "GLW",
    importance: "中高",
    status: "等待验证",
    marketExpect: "光纤+hyperscaler长协逻辑持续兑现",
    verifyPoint: "Optical Communications是否维持25-35%增长、hyperscaler长协是否转化为收入",
    impactPath: "若增长持续，GLW的AI材料基础设施溢价可能维持",
  },
  {
    date: "2026-Q3",
    title: "AXTI 6英寸InP研发进展",
    type: "产能",
    stocks: "AXTI",
    importance: "中",
    status: "等待验证",
    marketExpect: "6英寸InP客户认证进度",
    verifyPoint: "6英寸InP良率和客户认证是否如期推进",
    impactPath: "若进展顺利，AXTI的远期估值上限可能打开",
  },
  {
    date: "2026-09-中旬",
    title: "AVGO FY2026 Q3 财报",
    type: "财报",
    stocks: "AVGO",
    importance: "极高",
    status: "等待验证",
    marketExpect: "AI半导体增速、Q4指引、Networking占比",
    verifyPoint: "AI半导体收入是否继续超指引、FY2027目标是否上修、Networking占比是否提升",
    impactPath: "若FY2027目标上修，AVGO可能重获估值弹性；否则继续震荡消化",
  },
  {
    date: "2026-Q4",
    title: "AI服务器供应链订单兑现验证",
    type: "订单",
    stocks: "CRWV / VRT / HPE / DELL",
    importance: "高",
    status: "等待验证",
    marketExpect: "GB300/VR200量产对AI基建股的拉动",
    verifyPoint: "AI服务器订单是否持续放量、供应链业绩是否兑现",
    impactPath: "若订单持续超预期，AI基建股可能迎来第二轮估值上修",
  },
  {
    date: "2026-12",
    title: "稳定币法案立法窗口",
    type: "监管",
    stocks: "CRCL / COIN",
    importance: "高",
    status: "等待验证",
    marketExpect: "参议院审议进展",
    verifyPoint: "法案是否取得实质性进展、稳定币监管框架是否明确",
    impactPath: "若法案推进，CRCL的核心估值逻辑可能反转",
  },
  {
    date: "2027-H1",
    title: "TSEM 2027 SiPho 13亿美元合同收入确认",
    type: "订单",
    stocks: "TSEM",
    importance: "极高",
    status: "等待验证",
    marketExpect: "SiPho合同按期转收入、毛利率、产能利用率",
    verifyPoint: "2027年13亿美元SiPho收入合同是否按期确认、毛利率是否随规模扩张提升",
    impactPath: "若合同顺利兑现，TSEM估值体系可能从代工转向AI硅光平台",
  },
];

// 近期最重要的三件事
const topThree = [
  { date: "2026-06-10", title: "MU财报：验证HBM与DRAM涨价弹性", stocks: "MU / DRAM" },
  { date: "2026-06-25", title: "NVIDIA GTC中国站：验证CPO与AI Factory线索", stocks: "NVDA / LITE / COHR / AAOI" },
  { date: "2026-06中旬", title: "ASTS发射窗口：验证卫星部署节奏", stocks: "ASTS" },
];
