(() => {
'use strict';
const $ = s => document.querySelector(s), $$ = s => [...document.querySelectorAll(s)];
const esc = s => String(s ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const data = window.archiveData, all = [...articles].sort((a,b)=>b.date.localeCompare(a.date));
const byId = id => all.find(a=>a.id===id);
const tagged = (text, cls='') => `<span class="badge ${cls}">${esc(text)}</span>`;
const companyArticles = c => all.filter(a=>a.tags.some(t=>t===`个股:${c.id}`||t===`财报:${c.id}`)||c.ids.includes(a.id));
const eventArticles = e => e.articleIds.map(byId).filter(Boolean).sort((a,b)=>a.date.localeCompare(b.date));
const type = a => /财报|earnings/.test(a.title+' '+a.id) ? '财报分析' : /学习|术语|道德经|专业主义/.test(a.title) ? '学习笔记' : a.category==='近期热点'||/宏观|地缘/.test(a.subcategory||'') ? '事件观察' : a.tags.some(t=>/^(个股|财报):/.test(t)) ? '公司研究' : '产业理解';
const symbols = a => a.tags.filter(t=>/^(个股|财报):/.test(t)).map(t=>t.split(':')[1]);
const tagLinks = a => [...new Set(symbols(a))].slice(0,3).map(s=>data.companies.some(c=>c.id===s)?`<a class="tag" href="/research/${s.toLowerCase()}/">${esc(s)}</a>`:`<span class="tag">${esc(s)}</span>`).join('');
function articleRow(a,featured=false){
return `<article class="article-row ${featured?'featured':''}">${featured?'':`<time class="date" datetime="${esc(a.date)}">${a.date.slice(0,4)}<strong>${a.date.slice(5).replace('-','.')}</strong></time>`}<div>${featured?`<div class="featured-top"><span class="eyebrow">最近一篇 · LATEST ENTRY</span><span class="type-label">${type(a)}</span></div>`:`<span class="type-label">${type(a)}</span>`}<a href="${esc(a.file)}"><h3>${esc(a.title)}</h3><p>${esc(a.summary)}</p></a><div class="meta">${featured?`<time datetime="${a.date}">${a.date.replaceAll('-','.')}<span> · </span></time>`:''}<span>${esc(a.subcategory||a.category)}</span><div class="tags">${tagLinks(a)}</div><a class="arrow" href="${esc(a.file)}" aria-label="阅读${esc(a.title)}">↗</a></div></div></article>`;
}
function companyCard(c){const list=companyArticles(c);return `<a href="/research/${c.id.toLowerCase()}/" class="company-card"><header><span class="ticker">${c.id}</span><span>↗</span></header><h3>${esc(c.name)}</h3><p>${esc(c.sector)}</p><footer><span>${list.length?list.length+' 篇研究':'待补充资料'}</span><span>${list.length?'更新 '+list[0].date.slice(5).replace('-','.'):'独立档案空间'}</span></footer></a>`;}
function eventCard(e,i){return `<a class="event-card" href="/events/${e.id}/"><span class="event-num">EVENT ${String(i+1).padStart(3,'0')} · ${e.period}</span><h2>${e.title}</h2><p>${e.description}</p><div class="tags">${tagged(e.topic)}${tagged(e.status,'amber')}</div><footer><span>${eventArticles(e).length} 篇原有文章</span><span>回看档案 ↗</span></footer></a>`;}
function readingLink(a,i){return `<a class="reading-link" href="${a.file}"><span class="reading-num">${String(i+1).padStart(2,'0')}</span><div><h3>${esc(a.title)}</h3><p>${type(a)} · ${a.date}</p></div><span class="arrow">↗</span></a>`;}
function activate(selector,attr,value){$$(selector).forEach(b=>{const on=b.getAttribute(attr)===value;b.classList.toggle('active',on);b.setAttribute('aria-pressed',String(on));});}
let page=document.body.dataset.page;
const navKey={'event-detail':'events','company-detail':'research','hypothesis-detail':'learning','article':'','notes':''}[page]??page;
$$('[data-nav]').forEach(a=>{if(a.dataset.nav===navKey){a.classList.add('active');a.setAttribute('aria-current','page');}});
$('.mobile-menu')?.addEventListener('click',e=>{const open=$('.primary-nav').classList.toggle('open');e.currentTarget.setAttribute('aria-expanded',String(open));});
if(page==='home'){
$('#recent-articles').innerHTML=all.slice(0,4).map((a,i)=>articleRow(a,i===0)).join('');
$('#home-companies').innerHTML=['MU','NVDA','AVGO','ORCL'].map(id=>companyCard(data.companies.find(c=>c.id===id))).join('');
$('#evergreen').innerHTML=['optical-communication-learning-path','industry-glossary-2026','stagg-professionalism'].map(byId).filter(Boolean).map(readingLink).join('');
// Keep old homepage anchor links meaningful.
const redirects={'#tracking':'/research/','#frameworks':'/learning/','#calendar':'/calendar/','#notes':'/notes/','#contact':'/about/'};
if(redirects[location.hash])location.replace(redirects[location.hash]);
}
if(page==='events')$('#event-list').innerHTML=data.events.map(eventCard).join('');
const industries=[{title:'AI 基础设施',desc:'从算力、互联，到数据中心与电力。',pattern:/AI|GPU|算力|数据中心/,query:'AI'},{title:'存储与 HBM',desc:'供需、技术升级与财报预期的交汇。',pattern:/存储|HBM|DRAM/,query:'存储'},{title:'光通信与互联',desc:'沿着信号路径，理解产业价值链。',pattern:/光通信|光互联|光模块|InP/,query:'光通信'}];
if(page==='research'){
function renderResearch(mode){activate('[data-research]','data-research',mode);$('#research-list').innerHTML=mode==='companies'?data.companies.map(companyCard).join(''):industries.map((i,n)=>`<a class="company-card" href="/notes/?q=${encodeURIComponent(i.query)}"><span class="eyebrow">INDUSTRY ${String(n+1).padStart(2,'0')}</span><h3>${i.title}</h3><p>${i.desc}</p><footer><span>${all.filter(a=>JSON.stringify(a).includes(i.query)).length} 篇关联文章</span><span>按主题阅读 ↗</span></footer></a>`).join('');}
$$('[data-research]').forEach(b=>b.addEventListener('click',()=>renderResearch(b.dataset.research)));renderResearch('companies');
}
if(page==='notes'){
$('#article-search').value=new URLSearchParams(location.search).get('q')||'';
function filter(){const q=$('#article-search').value.trim().toLocaleLowerCase();const t=$('#article-type').value;const list=all.filter(a=>(!q||[a.title,a.summary,a.keywords,...a.tags].join(' ').toLocaleLowerCase().includes(q))&&(!t||type(a)===t));if($('#article-sort').value==='asc')list.reverse();$('#result-count').textContent=`${list.length} 篇文章 · 保留原文日期`;$('#article-results').innerHTML=list.length?list.map(a=>articleRow(a)).join(''):'<div class="empty">没有找到匹配内容，试试公司代码或更简短的关键词。</div>';const u=new URL(location.href);q?u.searchParams.set('q',$('#article-search').value):u.searchParams.delete('q');history.replaceState(null,'',u);}
$('#article-search').addEventListener('input',filter);$('#article-type').addEventListener('change',filter);$('#article-sort').addEventListener('change',filter);filter();
}
if(page==='event-detail'){
const e=data.events.find(e=>e.id===$('#main').dataset.event), list=eventArticles(e);let mode='review',step=0;
$('#event-detail').innerHTML=`<section class="detail-top"><a class="breadcrumb" href="/events/">← 所有事件档案</a><div class="eyebrow">EVENT ARCHIVE · ${e.period}</div><h1>${e.title}</h1><p>${e.question}</p><div class="tags">${tagged(e.status,'amber')}${tagged('2026-09-12 整理归档')}${e.companies.map(c=>`<a class="tag" href="/research/${c.toLowerCase()}/">${c} 公司档案 ↗</a>`).join('')}</div></section><div class="mode-tabs"><button data-mode="review" class="active" aria-pressed="true">复盘阅读</button><button data-mode="sequence" aria-pressed="false">按文章顺序回看</button></div><div class="notice" id="event-mode-notice"></div><div class="detail-layout"><section><div id="replay-controls"></div><div id="event-timeline"></div></section><aside class="detail-side" id="event-sidebar"></aside></div>`;
const timeline=a=>`<article class="timeline-row"><time>${a.date.replaceAll('-','.')} · 文章标注日期</time><div class="paper"><div class="tags">${tagged('原有文章 · 记录性质待核对','amber')}${tagged(type(a))}</div><h3>${esc(a.title)}</h3><p>${esc(a.summary)}</p><div class="record-grid"><div><h4>原始信息与观点</h4><p>按原文阅读；尚未逐条区分事实、机构观点与个人判断。</p></div><div><h4>实际行动</h4><p>尚未关联交易与仓位记录。文章中的策略讨论不等于已执行。</p></div></div><details><summary>时间与来源说明</summary><p>事件发生时间：未逐条核对。文章标注日期：${a.date}。首次获知/记录时间：未知。整理归档时间：${data.organizedAt}。</p></details><a href="${a.file}" class="text-link">阅读原文及其引用来源 ↗</a></div></article>`;
function renderEvent(){activate('[data-mode]','data-mode',mode);$('#event-mode-notice').textContent=mode==='review'?'这是一份基于原有文章的资料索引。连续行情、实际行动和最终复盘尚待补全。':'当前只按文章标注日期逐篇展示；原始记录时间未经核验，不能视为严格的“当时可见信息”回放。后续文章和总结不会提前展示。';$('#event-timeline').innerHTML=(mode==='review'?list:list.slice(0,step+1)).map(timeline).join('');$('#event-sidebar').innerHTML=mode==='review'?`<div class="paper"><h3>这份档案还缺什么</h3><ul>${e.gaps.map(g=>`<li>${g}</li>`).join('')}</ul><p>没有连续数据时，不用示意走势图替代真实行情。</p></div><div class="paper"><h3>关联的经验与假说</h3>${data.hypotheses.filter(h=>h.eventIds.includes(e.id)).map(h=>`<p><a href="/learning/${h.id}/">${h.title} ↗</a></p>`).join('')||'<p>还没有关联经验。</p>'}<p>关联资料不自动构成支持证据。</p></div><div class="paper"><h3>继续这份记录</h3><p>补充原始资料或新增修订，保留之前的判断。</p><a class="text-link" href="/workbench/?event=${e.id}">记录一条新观察 ↗</a></div>`:'<div class="paper"><h3>慢一点，逐篇回看</h3><p>在打开下一篇之前，想一想：现有材料支持什么？哪些部分仍然不确定？</p><p>这只是阅读辅助，不能消除旧文章中可能含有的事后解释。</p></div>';$('#replay-controls').innerHTML=mode==='sequence'?`<div class="replay-controls"><button id="previous-record" class="button secondary" ${step===0?'disabled':''}>上一步</button><span>已展开 ${step+1} / ${list.length} 篇</span><button id="next-record" class="button" ${step===list.length-1?'disabled':''}>下一篇 →</button></div>`:'';$('#previous-record')?.addEventListener('click',()=>{step--;renderEvent();});$('#next-record')?.addEventListener('click',()=>{step++;renderEvent();});}
$$('[data-mode]').forEach(b=>b.addEventListener('click',()=>{mode=b.dataset.mode;step=0;renderEvent();}));renderEvent();
}
if(page==='company-detail'){
const c=data.companies.find(c=>c.id===$('#main').dataset.company), list=companyArticles(c);let mode='time';
$('#company-detail').innerHTML=`<section class="detail-top"><a class="breadcrumb" href="/research/">← 研究档案</a><div class="eyebrow">COMPANY ARCHIVE · ${c.id}</div><h1>${c.name} <span class="ticker">${c.id}</span></h1><p>${c.sector}</p><div class="tags">${tagged(list.length+' 篇关联研究')}${tagged(list.length?'最近文章 '+list[0].date:'待补充资料','amber')}</div></section><div class="detail-layout"><section><div class="tabs"><button data-company-mode="time" class="active" aria-pressed="true">按时间看</button><button data-company-mode="question" aria-pressed="false">按问题看</button></div><div id="company-articles"></div></section><aside class="detail-side"><div class="paper"><h3>值得继续研究的问题</h3><p>${c.question}</p><p>页面导读于 2026-09-12 整理，不代表当时或当前的投资判断。</p></div><div class="paper"><h3>当前理解</h3><p>尚未补充经本人确认的最新研究摘要。可以先阅读历史文章，查看当时的观点与依据。</p></div><div class="paper"><h3>关联事件</h3>${data.events.filter(e=>e.companies.includes(c.id)).map(e=>`<p><a href="/events/${e.id}/">${e.title} ↗</a></p>`).join('')||'<p>暂未关联事件。</p>'}</div><div class="paper"><h3>原始资料与研报</h3><p>现有来源链接保留在各篇原文中；尚未单独导入附件。收藏研报不等于采纳其判断。</p><a class="text-link" href="/workbench/?company=${c.id}">补充研究记录 ↗</a></div></aside></div>`;
function renderCompany(){activate('[data-company-mode]','data-company-mode',mode);$('#company-articles').innerHTML=!list.length?'<div class="empty"><h3>这个空间，留给下一次研究。</h3><p>还没有收录该公司的文章。第一份研究、财报或资料，都可以成为起点。</p><a href="/workbench/?company='+c.id+'" class="button secondary">写下第一条记录</a></div>':mode==='time'?list.map(a=>articleRow(a)).join(''):['财报分析','公司研究','产业理解','事件观察','学习笔记'].map(t=>{const group=list.filter(a=>type(a)===t);return group.length?`<section><h2>${({'财报分析':'财报与业务兑现','公司研究':'基本面与竞争格局','产业理解':'产业与技术路径','事件观察':'市场预期与风险','学习笔记':'基础概念与方法'})[t]}</h2>${group.map(a=>articleRow(a)).join('')}</section>`:'';}).join('');}
$$('[data-company-mode]').forEach(b=>b.addEventListener('click',()=>{mode=b.dataset.companyMode;renderCompany();}));renderCompany();
}
if(page==='learning'){
function renderLearning(mode){activate('[data-learning]','data-learning',mode);$('#learning-list').innerHTML=mode==='notes'?`<div class="notice">基础学习与经验假说分开保存。以下来自已有学习文章；阅读顺序不代表已经完成学习。</div>${all.filter(a=>type(a)==='学习笔记').map(readingLink).join('')}`:`<div class="notice">以下三条由本次讨论整理成研究问题，状态均为“观察中”，尚未验证。关联文章仅为背景资料。</div>${data.hypotheses.map((h,i)=>`<article class="hypothesis-card"><span class="number">0${i+1}</span><div>${tagged('观察中','amber')}<a href="/learning/${h.id}/"><h2>${h.title}</h2></a><p>${h.boundary}</p><span class="muted">反例：待收集 · 整理于 2026.09.12</span></div><a href="/learning/${h.id}/" aria-label="打开${h.title}">↗</a></article>`).join('')}`;}
$$('[data-learning]').forEach(b=>b.addEventListener('click',()=>renderLearning(b.dataset.learning)));renderLearning('hypotheses');
}
if(page==='hypothesis-detail'){
const h=data.hypotheses.find(h=>h.id===$('#main').dataset.hypothesis);
$('#hypothesis-detail').innerHTML=`<section class="detail-top"><a class="breadcrumb" href="/learning/">← 学习与经验</a><div class="eyebrow">WORKING HYPOTHESIS</div><h1>${h.title}</h1><div class="tags">${tagged('观察中','amber')}${tagged('本次讨论整理 · 尚未验证')}</div></section><div class="detail-layout"><section><div class="paper"><h2>最初的观察</h2><p>${h.observation}</p><h2>适用边界</h2><p>${h.boundary}</p><h2>反例与失效条件</h2><p>${h.counter}</p><h2>下一次怎样验证</h2><p>${h.question}</p></div><div class="section-heading" style="margin-top:30px"><h2>背景阅读</h2></div>${h.articleIds.map(byId).filter(Boolean).map(readingLink).join('')||'<div class="empty">还没有关联资料。</div>'}</section><aside class="detail-side"><div class="paper"><h3>证据状态</h3><p>已确认支持案例：0</p><p>已确认反例：0</p><p>背景文章不自动计作验证案例。</p></div><div class="paper"><h3>版本记录</h3><p>2026-09-12 · v1</p><p>根据讨论整理原始观察与待验证问题；未经验证，不作为交易规则。</p></div><div class="paper"><h3>回到相关事件</h3>${h.eventIds.map(id=>data.events.find(e=>e.id===id)).map(e=>`<p><a href="/events/${e.id}/">${e.title} ↗</a></p>`).join('')||'<p>尚未关联。</p>'}</div></aside></div>`;
}
function localDate(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}
if(page==='calendar'){
const today=localDate();$('#calendar-month').value=today.slice(0,7);
[...new Set(calendarEvents.map(e=>e.type))].forEach(t=>$('#calendar-type').insertAdjacentHTML('beforeend',`<option>${esc(t)}</option>`));
function renderCalendar(){const month=$('#calendar-month').value,t=$('#calendar-type').value;const list=calendarEvents.filter(e=>e.date.startsWith(month)&&(!t||t===e.type)).sort((a,b)=>a.date.localeCompare(b.date));$('#calendar-results').innerHTML=list.length?list.map(e=>{const related=data.companies.filter(c=>new RegExp(`\\b${c.id}\\b`).test(e.stocks||''));return `<article class="calendar-row"><time>${e.date.replaceAll('-','.')}</time><div><div class="tags">${tagged(e.type)}${tagged(e.date<today?'历史日程 · 结果待补':'旧资料计划 · 待重新核验','amber')}${tagged(e.certainty==='confirmed'?'原记录：已确认':'原记录：预估')}</div><h3>${esc(e.title)}</h3><p>${esc(e.stocks)}</p><details><summary>当时准备验证什么</summary><div class="record-grid"><div><h4>原记录中的市场预期</h4><p>${esc(e.marketExpect)}</p></div><div><h4>待验证问题</h4><p>${esc(e.verifyPoint)}</p></div></div><p>原记录中的影响路径：${esc(e.impactPath)}</p></details><div class="tags">${related.map(c=>`<a class="tag" href="/research/${c.id.toLowerCase()}/">${c.name}研究 ↗</a>`).join('')}</div><p class="muted">实际结果与事后修订：尚未补充。</p></div></article>`;}).join(''):`<div class="empty"><h3>${esc(month.replace('-',' 年 '))} 月，暂无${t?'此类型的':'已录入'}日程。</h3><p>日历不会自动更新，也尚未开启通知。可查看已有历史记录，或先在工作台记下待验证事项。</p><a class="text-link" href="/workbench/">记录待验证事项 ↗</a></div>`;}
$('#calendar-month').addEventListener('change',renderCalendar);$('#calendar-type').addEventListener('change',renderCalendar);$('#calendar-current').addEventListener('click',()=>{$('#calendar-month').value=today.slice(0,7);renderCalendar();});$('#calendar-history').addEventListener('click',()=>{$('#calendar-month').value=[...calendarEvents].sort((a,b)=>b.date.localeCompare(a.date))[0]?.date.slice(0,7)||today.slice(0,7);$('#calendar-type').value='';renderCalendar();});renderCalendar();
}
if(page==='article'){
const id=location.pathname.split('/').filter(Boolean).at(-1),a=byId(id);
if(a){const companies=data.companies.filter(c=>companyArticles(c).some(n=>n.id===a.id));const events=data.events.filter(e=>e.articleIds.includes(a.id));const box=document.createElement('aside');box.className='archive-context';box.innerHTML=`<strong>研究上下文</strong> · 原文日期 ${a.date} · 首次记录时间与观点归属待核对<div class="tags">${companies.map(c=>`<a class="tag" href="/research/${c.id.toLowerCase()}/">${c.name}档案 ↗</a>`).join('')}${events.map(e=>`<a class="tag" href="/events/${e.id}/">${e.title} ↗</a>`).join('')}<a class="tag" href="/notes/">全部文章 ↗</a></div>`;$('.article-meta')?.after(box);}
}
if(page==='workbench'){
const KEY='xxyalpha.research-notebook.v1',KINDS=['当时记录','事后补记','历史研究'];let notes=[],storageOK=true;
try{const saved=localStorage.getItem(KEY);notes=saved?JSON.parse(saved):[];if(!Array.isArray(notes)||!notes.every(validNote))throw Error('invalid');}catch{storageOK=false;$('#save-status').textContent='无法读取草稿。为保护已有数据，已暂停保存；请先检查浏览器存储或备份文件。';}
const params=new URLSearchParams(location.search);$('#note-company').insertAdjacentHTML('beforeend',data.companies.map(c=>`<option value="${c.id}">${c.name} ${c.id}</option>`).join(''));$('#note-event').insertAdjacentHTML('beforeend',data.events.map(e=>`<option value="${e.id}">${e.title}</option>`).join(''));
$('#note-company').value=params.get('company')||'';$('#note-event').value=params.get('event')||'';$('#note-form [name=eventDate]').value=localDate();
function validNote(n){return n&&typeof n.id==='string'&&n.id.length<100&&typeof n.title==='string'&&n.title.length>0&&n.title.length<=160&&KINDS.includes(n.kind)&&/^\d{4}-\d{2}-\d{2}$/.test(n.eventDate)&&!isNaN(Date.parse(n.createdAt))&&['observed','judgment','action','source','company','event','revises'].every(k=>typeof n[k]==='string'&&n[k].length<50000);}
function persist(next){if(!storageOK)throw Error('storage unavailable');localStorage.setItem(KEY,JSON.stringify(next));notes=next;renderDrafts();}
function renderDrafts(){const sorted=[...notes].sort((a,b)=>b.createdAt.localeCompare(a.createdAt));$('#note-revises').innerHTML='<option value="">新记录（非修订）</option>'+notes.map(n=>`<option value="${esc(n.id)}">${esc(n.title)}</option>`).join('');$('#draft-list').innerHTML=sorted.length?sorted.map(n=>`<article class="draft-card">${tagged(n.kind)}${n.revises?tagged('修订记录','amber'):''}<h3>${esc(n.title)}</h3><p>事件日期 ${n.eventDate}<br>记录时间 ${esc(new Date(n.createdAt).toLocaleString('zh-CN'))}</p>${n.revises?`<p>修订自：${esc(notes.find(o=>o.id===n.revises)?.title||n.revises)}</p>`:''}<details><summary>查看完整记录</summary><h4>我看到了什么</h4><p>${esc(n.observed)}</p><h4>我的理解与疑问</h4><p>${esc(n.judgment||'未填写')}</p><h4>行动或观望</h4><p>${esc(n.action||'未填写')}</p><p>来源：${/^https?:\/\//i.test(n.source)?`<a class="text-link" href="${esc(n.source)}" target="_blank" rel="noopener noreferrer">查看来源 ↗</a>`:esc(n.source||'未填写')}</p><p>关联公司：${esc(n.company||'未关联')}<br>关联事件：${esc(data.events.find(e=>e.id===n.event)?.title||'未关联')}</p></details></article>`).join(''):'<div class="empty"><h3>从一条真实的观察开始。</h3><p>你的记录会保存在这里。无需写成完整文章。</p></div>';}
$('#note-form').addEventListener('submit',e=>{e.preventDefault();const n=Object.fromEntries(new FormData(e.currentTarget));n.id=crypto.randomUUID();n.createdAt=new Date().toISOString();if(!n.title.trim()||!n.observed.trim()){ $('#save-status').textContent='请填写标题和实际观察，不能只输入空格。';return;}if(!validNote(n)){ $('#save-status').textContent='记录格式有误，请检查日期和内容长度。';return;}if(n.source&&!/^https?:\/\//i.test(n.source)){$('#save-status').textContent='来源请使用 http 或 https 链接。';return;}try{persist([...notes,n]);e.currentTarget.reset();$('#note-form [name=eventDate]').value=localDate();$('#save-status').textContent='已保存到此浏览器，尚未发布。';}catch{$('#save-status').textContent='保存失败，可能是浏览器存储不可用或已满。请保留当前输入。';}});
function download(name,text){const a=document.createElement('a');const url=URL.createObjectURL(new Blob([text],{type:'application/json'}));a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
$('#export-notes').addEventListener('click',()=>{if(!storageOK){$('#save-status').textContent='当前无法读取原草稿，未导出；请先恢复存储访问。';return;}download(`xxyalpha-notes-${localDate()}.json`,JSON.stringify({version:1,exportedAt:new Date().toISOString(),notes},null,2));});
$('#import-notes').addEventListener('change',async e=>{const f=e.target.files[0];if(!f)return;try{if(f.size>5*1024*1024)throw Error();const imported=JSON.parse(await f.text());if(imported.version!==1||!Array.isArray(imported.notes)||!imported.notes.every(validNote))throw Error();const ids=new Set(notes.map(n=>n.id));const next=[...notes];let added=0;for(const n of imported.notes){if(!ids.has(n.id)){next.push(n);ids.add(n.id);added++;}else if(JSON.stringify(notes.find(old=>old.id===n.id))!==JSON.stringify(n)){throw Error('conflict');}}persist(next);$('#save-status').textContent=`已恢复 ${added} 条记录；已有记录保留。`;}catch{$('#save-status').textContent='恢复失败：文件格式不正确、记录冲突或存储不可用。原草稿没有被改写。';}e.target.value='';});renderDrafts();
}
})();
