// ========================================
// 市场速报数据 — 手动维护，按时间倒序
// ========================================

const newsItems = [
  {
    id: "n20260530-01",
    date: "2026-05-30",
    title: "英伟达 $4B 锁定 EML 供应，缺口或延至 2030",
    summary: "据传 Nvidia 以 $4B 长协锁定 Lumentum EML 产能，InP 缺口或延续至 2030 年。直接利好光互连上游光芯片和衬底环节。",
    impact: "利好",
    tags: ["光通信", "英伟达链"],
    stocks: ["LITE", "COHR", "AXTI"],
    detail: "据市场消息，Nvidia 与 Lumentum 签署了价值约 $4B 的长协合同，锁定 EML 激光器供应至 2030 年。这表明 AI 集群对光互联的需求不是短期故事，EML 和 InP 的紧缺可能持续数年。",
    source: "小红书 / 产业调研",
  },
  {
    id: "n20260529-01",
    date: "2026-05-29",
    title: "ASTS -18.6% 航天板块暴跌",
    summary: "ASTS 单日暴跌 18.6%，RKLB -6%，航天/卫星板块出现系统性卖出。原因待查。",
    impact: "利空",
    tags: ["航天"],
    stocks: ["ASTS", "RKLB"],
    detail: "ASTS 和 RKLB 周五同步暴跌，可能涉及 FCC 政策变化、SpaceX 相关消息或板块获利了结。成交额放大但非散户恐慌，更像机构一次性减仓。",
    source: "市场行情",
  },
  {
    id: "n20260529-02",
    date: "2026-05-29",
    title: "HOOD +9.8% SOFI +9.1% 金融平台全线爆发",
    summary: "金融科技平台连续两日暴涨，SOFI 单周涨超 20%，HOOD 突破前高。Call 期权新开仓集中。",
    impact: "利好",
    tags: ["金融科技"],
    stocks: ["HOOD", "SOFI"],
    detail: "HOOD 和 SOFI 周五继续放量上攻，期权市场出现多档 Call 异动（vol/oi 3-23x），新开仓为主。金融平台方向成为本周最强主线。",
    source: "市场行情 + 期权数据",
  },
  {
    id: "n20260529-03",
    date: "2026-05-29",
    title: "MSFT +3.7% Call 期权巨量开仓",
    summary: "MSFT 连续多日走强，$450/$470 Call 分别成交 1.8 万/2.3 万手，覆盖 $438-$505 共 12 档行权价，机构级别布局。",
    impact: "利好",
    tags: ["科技巨头"],
    stocks: ["MSFT"],
    detail: "MSFT 周五 $450 Call 成交 18,760 手、$470 Call 成交 23,674 手，覆盖从价内到 +14% OTM 的多个行权价，是典型的机构系统性买入。",
    source: "期权数据",
  },
  {
    id: "n20260529-04",
    date: "2026-05-29",
    title: "MU +4.8% 存储涨价逻辑延续",
    summary: "MU 放量上涨，Call 期权异动 8.3x，存储板块 DRAM ETF +1.2%。存储涨价趋势确认。",
    impact: "利好",
    tags: ["存储", "半导体"],
    stocks: ["MU", "DRAM"],
    detail: "MU 周五 +4.8%，$965 Call vol/oi 8.3x 且 OI 仅 124 手（新开仓），配合存储板块持续走强，涨价逻辑得到市场确认。",
    source: "市场行情 + 期权数据",
  },
  {
    id: "n20260528-01",
    date: "2026-05-28",
    title: "LITE/AXTI/AAOI 光互连组全线暴跌",
    summary: "光互连组周四大跌，AXTI -10.2%，AAOI -6%，LITE -4.6%。AAOI 144 内幕减持公告是主要触发因素。",
    impact: "利空",
    tags: ["光通信"],
    stocks: ["LITE", "AXTI", "AAOI", "COHR"],
    detail: "光互连组周四系统性杀跌，AAOI 前一日提交 144 表格（内幕减持预告）是主要触发因素。叠加 EML 逻辑获利了结，全板块一天跌去过去一周涨幅。",
    source: "SEC Filing + 市场行情",
  },
  {
    id: "n20260527-01",
    date: "2026-05-27",
    title: "高盛警告：$270 亿养老金月末再平衡",
    summary: "高盛报告称月末养老金再平衡 + 系统化策略反转可能导致约 $270 亿股票抛售。",
    impact: "中性",
    tags: ["宏观"],
    stocks: [],
    detail: "Goldman Sachs 发布报告警告美国企业养老金月末再平衡，叠加趋势跟踪策略反转，可能触发约 $270 亿的股票卖出。时间窗口在 5 月末 / 6 月初。",
    source: "Goldman Sachs / MarketWatch",
  },
];
