// ========================================
// 标的追踪数据 — 手动维护，手动更新
// ========================================

const trackingData = {

  // ──── A 股 ────
  "a-shares": [
    {
      id: "dongshan",
      code: "002384.SZ",
      name: "东山精密",
      sector: "PCB / 光通信",
      mkt: "a",
      type: "波段",
      color: "#f59e0b",
      reason: "PCB 龙头，AI 数据中心互联需求驱动，北美大客户导入中。",
      strategy: "回调至支撑位分批建仓，突破前高加仓。",
      stopLoss: null,
      targetPrice: null,
      lastUpdated: "2026-05-27",
      links: [],
      news: [
        { date: "2026-05-25", title: "公司公告：xxx", source: "公告" },
        { date: "2026-05-20", title: "PCB 行业景气度持续，AI 服务器需求拉动", source: "行业资讯" },
      ],
      earnings: [
        { period: "2026Q1", revenue: "85.6亿", netProfit: "5.2亿", grossMargin: "18.5%", yoy: "+12%" },
        { period: "2025Q4", revenue: "92.1亿", netProfit: "6.8亿", grossMargin: "19.2%", yoy: "+15%" },
      ],
      ratings: [
        { date: "2026-05-27", institution: "中信证券", rating: "买入", targetPrice: "—", change: "维持" },
        { date: "2026-05-20", institution: "中金公司", rating: "增持", targetPrice: "—", change: "维持" },
      ],
    },
    {
      id: "jianqiao",
      code: "603083.SH",
      name: "剑桥科技",
      sector: "光模块",
      mkt: "a",
      type: "长线",
      color: "#22c55e",
      reason: "光模块核心标的，受益于 800G / 1.6T 升级周期，北美客户订单放量。",
      strategy: "长线底仓不动，逢回调加仓，关注季报订单指引。",
      stopLoss: null,
      targetPrice: null,
      lastUpdated: "2026-05-26",
      links: [],
      news: [
        { date: "2026-05-26", title: "公司公告：xxx", source: "公告" },
      ],
      earnings: [],
      ratings: [],
    },
    {
      id: "hengtong",
      code: "600487.SH",
      name: "亨通光电",
      sector: "光纤光缆",
      mkt: "a",
      type: "长线",
      color: "#22c55e",
      reason: "光纤光缆龙头，数据中心互联 + 运营商招标双驱动。",
      strategy: "长线持有，关注海底光缆和海外业务进展。",
      stopLoss: null,
      targetPrice: null,
      lastUpdated: "2026-05-24",
      links: [],
      news: [],
      earnings: [],
      ratings: [],
    },
    {
      id: "yunnan",
      code: "002428.SZ",
      name: "云南锗业",
      sector: "新材料 / 锗",
      mkt: "a",
      type: "波段",
      color: "#f59e0b",
      reason: "锗资源龙头，InP/GaAs 衬底上游材料，光通信+红外双驱动。",
      strategy: "波段操作，关注锗价走势和出口政策变化。",
      stopLoss: null,
      targetPrice: null,
      lastUpdated: "2026-05-22",
      links: [],
      news: [],
      earnings: [],
      ratings: [],
    },
    {
      id: "hangtian",
      code: "002025.SZ",
      name: "航天电器",
      sector: "军工航天",
      mkt: "a",
      type: "长线",
      color: "#22c55e",
      reason: "航天连接器龙头，军工订单稳定增长，卫星互联网新增长点。",
      strategy: "长线持有，关注军工订单周期和卫星互联网配套进展。",
      stopLoss: null,
      targetPrice: null,
      lastUpdated: "2026-05-20",
      links: [],
      news: [],
      earnings: [],
      ratings: [],
    },
  ],

  // ──── 美股 ────
  "us-stocks": [
    {
      id: "lite",
      code: "LITE",
      name: "Lumentum",
      sector: "光通信 / 光源",
      mkt: "us",
      type: "波段",
      color: "#f59e0b",
      reason: "AI 光互连核心标的，EML 激光器 + 硅光技术领先，800G/1.6T 周期受益。",
      strategy: "波段操作，关注云厂商 CapEx 指引和光模块订单。",
      stopLoss: null,
      targetPrice: null,
      lastUpdated: "2026-05-27",
      links: [],
      news: [],
      earnings: [],
      ratings: [],
    },
    {
      id: "cohr",
      code: "COHR",
      name: "Coherent",
      sector: "光通信 / 激光器",
      mkt: "us",
      type: "监控",
      color: "#6366f1",
      reason: "光通信+材料+激光器多业务平台，AI 数据中心需求催化。",
      strategy: "保持监控，等待合适买点。",
      stopLoss: null,
      targetPrice: null,
      lastUpdated: "2026-05-26",
      links: [],
      news: [],
      earnings: [],
      ratings: [],
    },
    {
      id: "aaoi",
      code: "AAOI",
      name: "Applied Optoelectronics",
      sector: "光模块",
      mkt: "us",
      type: "波段",
      color: "#f59e0b",
      reason: "数据中心光模块供应商，受益 AI 集群互联需求。",
      strategy: "波段操作，关注订单公告和客户验证进展。",
      stopLoss: null,
      targetPrice: null,
      lastUpdated: "2026-05-25",
      links: [],
      news: [],
      earnings: [],
      ratings: [],
    },
    {
      id: "axti",
      code: "AXTI",
      name: "AXT Inc.",
      sector: "衬底材料",
      mkt: "us",
      type: "监控",
      color: "#6366f1",
      reason: "InP/GaAs 衬底龙头，AI 光模块上游关键材料。",
      strategy: "保持监控，关注衬底认证和出货量。",
      stopLoss: null,
      targetPrice: null,
      lastUpdated: "2026-05-24",
      links: [],
      news: [],
      earnings: [],
      ratings: [],
    },
    {
      id: "mrvl",
      code: "MRVL",
      name: "Marvell Technology",
      sector: "数据中心芯片",
      mkt: "us",
      type: "监控",
      color: "#6366f1",
      reason: "数据中心芯片（交换/DPU/PHY），光互连生态链关键节点。",
      strategy: "保持监控，关注定制 ASIC 进展和光模块配套。",
      stopLoss: null,
      targetPrice: null,
      lastUpdated: "2026-05-23",
      links: [],
      news: [],
      earnings: [],
      ratings: [],
    },
  ],
};
