// ========================================
// 标的追踪数据 — 手动维护，手动更新
// ========================================

const trackingData = {

  // ──── A 股 ────
  "a-shares": [
    {
      id: "dongshan",
      code: "002384.SZ",
      name: "东山精密",
      sector: "PCB / 光通信",
      mkt: "a",
      type: "波段",
      trackingStatus: "持有中",
      tradeCycle: "中线 / 波段",
      themeTags: "AI PCB / 光模块 / 北美客户",
      logicStatus: "逻辑增强",
      color: "#f59e0b",
      reason: "AI PCB + 光模块双主线，正在从消费电子周期股被重新定价为AI基础设施成长股。",
      strategy: "中线波段，回踩关键支撑或财报验证后分批配置。",
      stopLoss: null,
      targetPrice: null,
      lastUpdated: "2026-05-29",
      // ---- 投资逻辑 ----
      investmentLogic: {
        oneLiner: "东山精密正在从传统消费电子/FPC公司，向AI PCB + 光模块双主线切换；如果AI服务器高端PCB和光模块订单持续兑现，公司可能从周期制造股被重新定价为AI基础设施链条成长股。",
        currentHypothesis: "AI数据中心建设带动高速高频PCB、光模块需求增长，东山精密通过Multek等PCB能力和索尔思光电等光通信资产切入AI基础设施链条，未来业绩增长不再只依赖传统消费电子，而是由AI PCB和光模块共同驱动。",
        coreReason: [
          "AI PCB主线：AI服务器/交换机/数据中心互联升级，需要更高层数、更高频、更低损耗的PCB，若稳定进入核心客户供应链，收入和估值弹性可能提升。",
          "光模块主线：收购索尔思后具备光模块/光芯片相关布局，成为第二条AI基础设施主线。",
          "业绩已有验证：2026Q1营收和归母净利润大幅增长，AI相关业务已开始反映到财报。",
          "定价正在切换：市场正在从消费电子周期股转向AI PCB + 光模块 + 北美客户 + 算力基础设施逻辑重估。",
          "关键在持续性：后续要看AI PCB和光模块能否持续贡献收入、毛利率和现金流。"
        ],
        status: "逻辑增强，但进入估值和情绪验证阶段",
        statusNote: "业绩层面已有验证；AI PCB和光模块仍处高景气链条；但股价若已大幅反映预期，后续需要订单、毛利率和现金流继续确认。",
        validUntil: "2026Q2 - 2026Q4",
        validNote: "重点看：2026年中报；2026Q3订单延续性；AI PCB客户导入进展；光模块业务是否延续高增长；PCB板块行情是否进入后排补涨和退潮阶段。",
        questionsToVerify: [
          "AI PCB收入是否继续放量？",
          "光模块业务高增长是否可持续？",
          "毛利率是否继续改善？",
          "经营现金流是否跟得上利润？",
          "北美客户导入是否有更明确证据？",
          "当前估值是否已经提前透支2026年业绩？"
        ]
      },
      // ---- 催化剂看板 ----
      catalysts: [
        {
          catalyst: "2026年中报验证",
          timeWindow: "2026Q2 / 中报",
          importance: "高",
          status: "跟踪中",
          evidence: "AI PCB、光模块收入增长；毛利率改善；现金流不恶化",
          direction: "强正面 / 强负面"
        },
        {
          catalyst: "AI PCB客户导入进展",
          timeWindow: "1-3个月",
          importance: "高",
          status: "跟踪中",
          evidence: "公告、调研纪要、财报表述、订单或产能扩张",
          direction: "正面"
        },
        {
          catalyst: "光模块订单延续",
          timeWindow: "1-2个季度",
          importance: "高",
          status: "正在兑现",
          evidence: "索尔思并表后收入持续增长，而不是一次性高增",
          direction: "正面"
        },
        {
          catalyst: "PCB板块继续扩散",
          timeWindow: "短期",
          importance: "中高",
          status: "进行中",
          evidence: "沪电、胜宏、生益、华正、东山等强势联动",
          direction: "正面 / 过热"
        },
        {
          catalyst: "高速材料升级趋势",
          timeWindow: "中期",
          importance: "中高",
          status: "跟踪中",
          evidence: "M9/M10、PTFE、二代布、Q布方案推进",
          direction: "正面"
        },
        {
          catalyst: "财报低于高预期",
          timeWindow: "中报 / 三季报",
          importance: "高",
          status: "风险观察",
          evidence: "收入、毛利率、现金流任一核心指标低于市场预期",
          direction: "强负面"
        },
      ],
      // ---- 操作计划 ----
      operationPlan: {
        currentStatus: "重点观察 / 不适合无脑追高 / 等待回踩或财报继续验证。如果已经持有：继续跟踪，不因短线波动轻易下车。如果还没持有：等回踩、板块分歧或财报验证后的二次买点。",
        buyPlan: [
          "第一买点：回踩关键支撑后企稳——回踩20日线或前期平台，缩量止跌，板块龙头没有明显退潮。",
          "第二买点：财报验证后再加——中报继续高增长，毛利率改善，经营现金流没有恶化。",
          "不买条件：连续大涨后放量滞涨，板块后排乱炒，只靠小作文推动没有订单或财报验证。"
        ],
        addConditions: "财报继续验证AI PCB和光模块放量；毛利率、现金流、应收账款没有恶化；板块龙头仍强，股价回踩后重新放量。",
        reduceConditions: "短期涨幅明显透支基本面；利好不涨出现放量滞涨；PCB板块进入一致性高潮或后排乱炒；财报低于高预期。",
        invalidateConditions: "AI PCB和光模块收入无法持续兑现；毛利率和现金流没有改善；北美客户导入低于预期；板块龙头退潮，公司只剩补涨属性；市场重新把公司定价为传统消费电子/FPC周期股。"
      },
    },
    {
      id: "jianqiao",
      code: "603083.SH",
      name: "剑桥科技",
      sector: "光模块",
      mkt: "a",
      type: "中线",
      trackingStatus: "观察中 / 计划买入",
      tradeCycle: "中线 + 波段做T",
      themeTags: "高速光模块 / 800G / 1.6T / 硅光 / CPO / AI数据中心互联",
      logicStatus: "逻辑增强",
      priority: "高",
      color: "#6366f1",
      reason: "高速光模块进入业绩兑现期，800G贡献弹性，1.6T决定下一轮估值弹性。",
      strategy: "逢低布局，大跌企稳买入，大涨分批T出。",
      stopLoss: null,
      targetPrice: null,
      lastUpdated: "2026-05-29",
      investmentLogic: {
        oneLiner: "剑桥科技的核心不是蹭CPO概念，而是高速光模块已经进入业绩兑现期；当前800G贡献主要收入弹性，1.6T决定下一轮估值弹性，后续重点看订单、产能、毛利率和现金流能否继续兑现。",
        currentHypothesis: "AI数据中心网络从400G向800G、1.6T升级，带动高速光模块需求放量。剑桥科技如果在800G持续交付的基础上顺利推进1.6T量产和产能扩张，有机会从通信设备制造商重估为AI光互联链条的高弹性标的。",
        coreReason: [
          "业绩已经从概念进入兑现期：2026Q1营收和归母净利润大幅增长，核心驱动来自高速光模块业务规模提升。",
          "800G是当前主力：AI数据中心高速互联需求仍在放量，800G仍是现阶段最重要的出货和收入来源。",
          "1.6T决定下一阶段弹性：如果1.6T从小批量、验证阶段进入规模交付，公司估值弹性可能进一步打开。",
          "产能和交付能力是关键变量：高速光模块不是只看订单，还要看产能、良率、关键物料供应和交付节奏。",
          "高弹性伴随高波动：剑桥科技属于A股光模块链条中情绪和业绩弹性都较强的标的，更适合跟踪节奏和波段，不适合高位无脑追。"
        ],
        status: "逻辑增强，但属于高弹性、高波动、强验证标的",
        statusNote: "业绩层面已有高速光模块放量验证；行业层面800G/1.6T仍处在AI算力互联升级周期；但股价弹性大，容易受板块情绪、CPO预期、机构观点和小作文影响。",
        validUntil: "2026Q2 - 2026Q4",
        validNote: "重点看：2026年中报是否继续高增长；800G订单是否延续；1.6T出货占比是否提升；产能扩张是否顺利；毛利率是否维持稳定；经营现金流是否改善；光模块板块是否进入一致性过热阶段。",
        questionsToVerify: [
          "800G订单是否持续，而不是短期集中拉货？",
          "1.6T是否真正从验证、小批量走向规模交付？",
          "产能扩张是否能跟上订单需求？",
          "高速光模块毛利率能否维持？",
          "经营现金流能否改善？",
          "当前股价是否已经提前反映1.6T放量预期？"
        ]
      },
      catalysts: [
        { catalyst: "2026年中报验证", timeWindow: "2026Q2 / 中报", importance: "高", status: "跟踪中", evidence: "高速光模块收入继续增长，利润增速不明显回落", direction: "强正面 / 强负面" },
        { catalyst: "1.6T出货占比提升", timeWindow: "2026年内", importance: "高", status: "核心跟踪", evidence: "1.6T从验证/小批量转向持续规模交付", direction: "强正面" },
        { catalyst: "800G订单延续", timeWindow: "1-2个季度", importance: "高", status: "正在兑现", evidence: "800G仍是出货主力，订单没有明显回落", direction: "正面" },
        { catalyst: "产能扩张落地", timeWindow: "1-3个季度", importance: "中高", status: "推进中", evidence: "产能扩张顺利，交付能力提升", direction: "正面" },
        { catalyst: "毛利率维持稳定", timeWindow: "中报 / 三季报", importance: "高", status: "待验证", evidence: "高速光模块毛利率不因竞争或扩产明显下滑", direction: "强正面" },
        { catalyst: "现金流改善", timeWindow: "中报 / 三季报", importance: "高", status: "风险观察", evidence: "经营现金流改善，应收和库存没有失控", direction: "正面 / 负面" },
        { catalyst: "光模块板块过热", timeWindow: "短期", importance: "中高", status: "风险观察", evidence: "中际、新易盛、天孚、剑桥等集体加速，后排乱炒", direction: "短期负面" },
        { catalyst: "关键物料受限", timeWindow: "持续跟踪", importance: "高", status: "风险观察", evidence: "硅光芯片、CW光源、DSP等供应紧张影响交付", direction: "负面" },
      ],
      operationPlan: {
        currentStatus: "当前振幅巨大，适合逢低布局、波段做T。",
        buyPlan: ["大跌企稳买入。"],
        addConditions: "回调后缩量企稳，板块主线没有走坏，可考虑加仓。",
        reduceConditions: "大涨后分批T出，避免高位追涨和情绪回落。",
        invalidateConditions: "800G/1.6T订单不及预期；毛利率或现金流明显恶化；光模块板块龙头退潮；公司重新变成情绪补涨标的，而不是高速光模块兑现标的。"
      },
    },
    {
      id: "hengtong",
      code: "600487.SH",
      name: "亨通光电",
      sector: "光纤光缆",
      mkt: "a",
      type: "中线",
      trackingStatus: "观察中 / 计划买入",
      tradeCycle: "中线 + 波段",
      themeTags: "光纤光缆 / 光棒涨价 / 海底光缆 / 海洋能源 / AI算力网络",
      logicStatus: "逻辑增强",
      priority: "高",
      color: "#6366f1",
      reason: "光纤光缆量价齐升+海底光缆高壁垒+海外需求扩张，从传统周期股重新定价为AI算力网络基础设施龙头。",
      strategy: "逢低布局、趋势持有、波段做T。",
      stopLoss: null,
      targetPrice: null,
      lastUpdated: "2026-05-29",
      investmentLogic: {
        oneLiner: "亨通光电不是纯光模块弹性票，而是光纤光缆涨价+海底光缆订单+AI算力网络建设+海洋能源交付共同驱动的光通信基础设施龙头；核心看点是光纤从传统运营商耗材，重新被市场定价为AI算力网络的物理动脉。",
        currentHypothesis: "AI算力中心、跨数据中心互联、运营商算力网络建设和海外通信基础设施投资，会带动光纤光缆需求与价格同步修复；叠加海底光缆、海洋能源、海外订单交付，亨通光电的利润弹性不再只来自传统光纤周期，而是来自光通信景气反转+海洋业务高壁垒+海外需求扩张的组合重估。",
        coreReason: [
          "光纤光缆进入量价齐升阶段：AI数据中心和算力网络建设推高光纤需求，光棒扩产周期长、供给刚性，带来价格反转和盈利修复。证券时报报道，2026年光纤产业正经历需求爆发、供给刚性、价格反转的三重拐点。",
          "业绩已经明显兑现：2026Q1营收177.91亿元同比+34%，归母净利润11.05亿元同比+98.53%，扣非净利润11.33亿元同比+107.68%。增长来自光通信需求增长、价格上涨、海洋通信及能源产品交付增加、海外市场需求扩张。",
          "订单储备支撑后续：截至2026Q1末，能源互联领域订单约220亿元，海洋通信业务订单约70亿元，PEACE跨洋海缆项目订单超3亿美元，后续收入确认具备可见度。",
          "海底光缆是高壁垒业务：全球约40%海底光缆进入生命周期尾期，AI算力和跨洋数据传输需求推动新一轮国际海缆建设。公司是全球前四、且是中国唯一具备万公里级跨洋海底光缆系统综合解决方案能力的企业。",
          "风险在现金流和预期差：2026Q1应收账款187.20亿元，经营现金流转负，财务费用同比+122.93%。不能只看利润增速，需关注回款、扩张和融资成本压力。"
        ],
        status: "逻辑增强，但已进入业绩兑现+涨价持续性+现金流验证阶段",
        statusNote: "光纤光缆价格反转和AI算力网络需求提供行业贝塔；海缆和海洋能源订单提供中期确定性；但股价若已充分反映光纤涨价和Q1高增，后续需看中报、价格持续性、现金流和订单交付。",
        validUntil: "2026Q2 - 2026Q4",
        validNote: "重点看：中报是否延续高增长；光纤光缆涨价能否持续；光棒供给是否仍然紧张；海底光缆和海洋能源订单交付节奏；应收账款和经营现金流是否改善；光通信板块是否从光纤龙头扩散到后排后进入退潮。",
        questionsToVerify: [
          "光纤光缆涨价是否能持续，而不是短期脉冲？",
          "光棒供给紧张是否继续支撑价格？",
          "海洋通信和能源订单是否按节奏交付？",
          "Q1高增长是否能在中报继续兑现？",
          "应收账款和经营现金流是否改善？",
          "海外订单增长能否抵消国内运营商周期波动？",
          "当前估值是否已经提前反映光纤涨价和海缆订单预期？"
        ]
      },
      catalysts: [
        { catalyst: "2026年中报验证", timeWindow: "2026Q2 / 中报", importance: "高", status: "跟踪中", evidence: "收入、扣非利润继续增长；毛利率维持；现金流改善", direction: "强正面 / 强负面" },
        { catalyst: "光纤光缆涨价持续", timeWindow: "1-2个季度", importance: "高", status: "正在兑现", evidence: "G.652.D、G.657.A2等价格维持高位，运营商集采价继续上修", direction: "强正面" },
        { catalyst: "光棒供给紧张", timeWindow: "持续跟踪", importance: "高", status: "跟踪中", evidence: "光棒产能利用率高，新产能投放有限，供给没有明显松动", direction: "正面" },
        { catalyst: "海底光缆订单交付", timeWindow: "1-3个季度", importance: "高", status: "正在兑现", evidence: "海洋通信订单确认收入，PEACE等项目继续推进", direction: "正面" },
        { catalyst: "海洋能源订单确认", timeWindow: "1-3个季度", importance: "中高", status: "跟踪中", evidence: "海上风电、能源互联订单交付增加", direction: "正面" },
        { catalyst: "海外市场需求扩张", timeWindow: "中期", importance: "中高", status: "跟踪中", evidence: "海外光通信、海缆、电网订单继续增长", direction: "正面" },
        { catalyst: "现金流改善", timeWindow: "中报 / 三季报", importance: "高", status: "风险观察", evidence: "经营现金流转好，应收账款增速低于收入增速", direction: "强正面 / 负面" },
        { catalyst: "光通信板块过热", timeWindow: "短期", importance: "中高", status: "风险观察", evidence: "长飞、亨通、中天、通鼎等集体加速，后排补涨明显", direction: "短期负面" },
      ],
      operationPlan: {
        currentStatus: "当前属于光通信主线核心标的，但不是纯情绪小票，适合逢低布局、趋势持有、波段做T。",
        buyPlan: ["板块分歧或大跌企稳买入，重点看光纤涨价、海缆订单和中报验证。"],
        addConditions: "光纤价格继续上行，海洋业务订单兑现，中报利润和现金流同步改善。",
        reduceConditions: "大涨后分批T出；若利好不涨、光纤价格松动或现金流继续恶化，降低仓位。",
        invalidateConditions: "光纤涨价无法持续，行业重回低价竞争；海底光缆和海洋能源订单交付低于预期；Q1高增长无法在中报延续；应收账款继续上升，经营现金流持续恶化；光通信板块退潮，公司从主线龙头变成周期补涨标的。"
      },
    },
    {
      id: "yunnan",
      code: "002428.SZ",
      name: "云南锗业",
      sector: "新材料 / 锗",
      mkt: "a",
      type: "波段",
      color: "#f59e0b",
      reason: "锗资源龙头，InP/GaAs 衬底上游材料，光通信+红外双驱动。",
      strategy: "波段操作，关注锗价走势和出口政策变化。",
      stopLoss: null,
      targetPrice: null,
      lastUpdated: "2026-05-22",
      investmentLogic: null,
      catalysts: [],
      operationPlan: null,
    },
    {
      id: "hangtian",
      code: "002025.SZ",
      name: "航天电器",
      sector: "军工航天",
      mkt: "a",
      type: "长线",
      color: "#22c55e",
      reason: "航天连接器龙头，军工订单稳定增长，卫星互联网新增长点。",
      strategy: "长线持有，关注军工订单周期和卫星互联网配套进展。",
      stopLoss: null,
      targetPrice: null,
      lastUpdated: "2026-05-20",
      investmentLogic: null,
      catalysts: [],
      operationPlan: null,
    },
  ],

  // ──── 美股 ────
  "us-stocks": [
    {
      id: "lite",
      code: "LITE",
      name: "Lumentum",
      sector: "光通信 / 光源",
      mkt: "us",
      type: "波段",
      color: "#f59e0b",
      reason: "AI 光互连核心标的，EML 激光器 + 硅光技术领先，800G/1.6T 周期受益。",
      strategy: "波段操作，关注云厂商 CapEx 指引和光模块订单。",
      stopLoss: null,
      targetPrice: null,
      lastUpdated: "2026-05-27",
      investmentLogic: {
        oneLiner: "AI 光互连上游稀缺标的，光源/接收器/调制器全栈布局。",
        currentHypothesis: "800G EML 激光器供不应求 + 1.6T 硅光方案客户导入 → 营收加速。",
        coreReason: "LITE 是少数能同时提供 EML（外调制）+ 硅光（集成）方案的光器件公司，AI 互联升级双重受益。",
        status: "波段操作中",
        validUntil: "2026-09",
        questionsToVerify: "云厂商 CapEx 是否持续上修？1.6T 硅光模组何时获得大客户认证？"
      },
      catalysts: [
        {
          catalyst: "下季度营收指引上修",
          timeWindow: "2026年8月（Q4 财报）",
          importance: "高",
          status: "等待中",
          evidence: "营收指引环比增长 > 15%，云厂商光模块订单可见度延长",
          direction: "利好"
        },
      ],
      operationPlan: {
        currentStatus: "波段持仓中",
        buyPlan: "回调至 50 日线附近回补",
        addConditions: "股价缩量回踩支撑位 + 行业催化剂临近",
        reduceConditions: "连续 3 日放量不创新高，减半",
        invalidateConditions: "云厂商 CapEx 指引下修；竞争格局恶化（份额流失）",
        maxPosition: "总仓位的 12%"
      },
    },
    {
      id: "cohr",
      code: "COHR",
      name: "Coherent",
      sector: "光通信 / 激光器",
      mkt: "us",
      type: "监控",
      color: "#6366f1",
      reason: "光通信+材料+激光器多业务平台，AI 数据中心需求催化。",
      strategy: "保持监控，等待合适买点。",
      stopLoss: null,
      targetPrice: null,
      lastUpdated: "2026-05-26",
      investmentLogic: null,
      catalysts: [],
      operationPlan: null,
    },
    {
      id: "aaoi",
      code: "AAOI",
      name: "Applied Optoelectronics",
      sector: "光模块",
      mkt: "us",
      type: "波段",
      color: "#f59e0b",
      reason: "数据中心光模块供应商，受益 AI 集群互联需求。",
      strategy: "波段操作，关注订单公告和客户验证进展。",
      stopLoss: null,
      targetPrice: null,
      lastUpdated: "2026-05-25",
      investmentLogic: null,
      catalysts: [],
      operationPlan: null,
    },
    {
      id: "axti",
      code: "AXTI",
      name: "AXT Inc.",
      sector: "衬底材料",
      mkt: "us",
      type: "监控",
      color: "#6366f1",
      reason: "InP/GaAs 衬底龙头，AI 光模块上游关键材料。",
      strategy: "保持监控，关注衬底认证和出货量。",
      stopLoss: null,
      targetPrice: null,
      lastUpdated: "2026-05-24",
      investmentLogic: null,
      catalysts: [],
      operationPlan: null,
    },
    {
      id: "mrvl",
      code: "MRVL",
      name: "Marvell Technology",
      sector: "数据中心芯片",
      mkt: "us",
      type: "监控",
      color: "#6366f1",
      reason: "数据中心芯片（交换/DPU/PHY），光互连生态链关键节点。",
      strategy: "保持监控，关注定制 ASIC 进展和光模块配套。",
      stopLoss: null,
      targetPrice: null,
      lastUpdated: "2026-05-23",
      investmentLogic: null,
      catalysts: [],
      operationPlan: null,
    },
  ],
};
