// ========================================
// 标的追踪数据 — 手动维护，手动更新
// ========================================

const trackingData = {

  // ──── A 股 ────
  "a-shares": [
    {
      id: "dongshan",
      code: "002384.SZ",
      name: "东山精密",
      sector: "PCB / 光通信",
      mkt: "a",
      type: "波段",
      color: "#f59e0b",
      reason: "PCB 龙头，AI 数据中心互联需求驱动，北美大客户导入中。",
      strategy: "回调至支撑位分批建仓，突破前高加仓。",
      stopLoss: null,
      targetPrice: null,
      lastUpdated: "2026-05-27",
      // ---- 投资逻辑 ----
      investmentLogic: {
        oneLiner: "AI 数据中心拉动 PCB 高端需求，公司作为内资 PCB 龙头直接受益。",
        currentHypothesis: "北美大客户导入 + 高端 HDI/封装基板产能扩张 → 量价齐升。",
        coreReason: "PCB 是 AI 服务器和交换机不可或缺的基础硬件，东山在软板/硬板/封装基板三线布局齐全。",
        status: "验证中",
        validUntil: "2026-08",
        questionsToVerify: "北美大客户 Q3 是否开始批量供货？封装基板良率是否达到盈亏平衡？"
      },
      // ---- 催化剂看板 ----
      catalysts: [
        {
          catalyst: "北美大客户 PCB 批量供货公告",
          timeWindow: "2026年6-7月",
          importance: "高",
          status: "待确认",
          evidence: "客户认证公告或供应链调研确认量产排期",
          direction: "利好"
        },
        {
          catalyst: "Q2 财报——封装基板业务收入披露",
          timeWindow: "2026年8月",
          importance: "中",
          status: "等待中",
          evidence: "封装基板营收占比是否提升至 10% 以上，毛利率趋势",
          direction: "中性"
        },
      ],
      // ---- 操作计划 ----
      operationPlan: {
        currentStatus: "底仓持有，等待回踩加仓",
        buyPlan: "回调至 20 日线附近分批建仓底仓",
        addConditions: "北美大客户公告确认 + 股价放量突破前高",
        reduceConditions: "连续 3 日缩量滞涨，减 1/3 T 仓",
        invalidateConditions: "北美大客户导入失败或大幅延期；封装基板量产持续亏损",
        maxPosition: "总仓位的 15%"
      },
    },
    {
      id: "jianqiao",
      code: "603083.SH",
      name: "剑桥科技",
      sector: "光模块",
      mkt: "a",
      type: "长线",
      color: "#22c55e",
      reason: "光模块核心标的，受益于 800G / 1.6T 升级周期，北美客户订单放量。",
      strategy: "长线底仓不动，逢回调加仓，关注季报订单指引。",
      stopLoss: null,
      targetPrice: null,
      lastUpdated: "2026-05-26",
      investmentLogic: {
        oneLiner: "800G→1.6T 升级周期中，光模块环节确定性最强。",
        currentHypothesis: "北美云厂商 800G 需求持续放量 + 1.6T 开始小批量出货 → 营收和毛利率双升。",
        coreReason: "光模块是 AI 集群互联瓶颈环节，剑桥在数通光模块有核心客户关系。",
        status: "持有中",
        validUntil: "2026-12",
        questionsToVerify: "1.6T 产品何时进入量产？毛利率能否维持在 35% 以上？"
      },
      catalysts: [
        {
          catalyst: "800G 订单指引更新",
          timeWindow: "2026年6-7月",
          importance: "高",
          status: "等待中",
          evidence: "季报或公告中的 800G 出货量指引边际变化",
          direction: "利好"
        },
        {
          catalyst: "1.6T 光模块客户认证",
          timeWindow: "2026年H2",
          importance: "高",
          status: "待确认",
          evidence: "客户认证公告或行业调研信息",
          direction: "利好"
        },
      ],
      operationPlan: {
        currentStatus: "底仓已建，等待回调加仓",
        buyPlan: "长线底仓已建，剩余仓位等回调至 60 日线",
        addConditions: "800G 出货指引超预期 + 股价站稳前高",
        reduceConditions: "逻辑未破坏，不减仓",
        invalidateConditions: "1.6T 认证失败或大幅落后同业；核心客户流失",
        maxPosition: "总仓位的 20%"
      },
    },
    {
      id: "hengtong",
      code: "600487.SH",
      name: "亨通光电",
      sector: "光纤光缆",
      mkt: "a",
      type: "长线",
      color: "#22c55e",
      reason: "光纤光缆龙头，数据中心互联 + 运营商招标双驱动。",
      strategy: "长线持有，关注海底光缆和海外业务进展。",
      stopLoss: null,
      targetPrice: null,
      lastUpdated: "2026-05-24",
      investmentLogic: null,
      catalysts: [],
      operationPlan: null,
    },
    {
      id: "yunnan",
      code: "002428.SZ",
      name: "云南锗业",
      sector: "新材料 / 锗",
      mkt: "a",
      type: "波段",
      color: "#f59e0b",
      reason: "锗资源龙头，InP/GaAs 衬底上游材料，光通信+红外双驱动。",
      strategy: "波段操作，关注锗价走势和出口政策变化。",
      stopLoss: null,
      targetPrice: null,
      lastUpdated: "2026-05-22",
      investmentLogic: null,
      catalysts: [],
      operationPlan: null,
    },
    {
      id: "hangtian",
      code: "002025.SZ",
      name: "航天电器",
      sector: "军工航天",
      mkt: "a",
      type: "长线",
      color: "#22c55e",
      reason: "航天连接器龙头，军工订单稳定增长，卫星互联网新增长点。",
      strategy: "长线持有，关注军工订单周期和卫星互联网配套进展。",
      stopLoss: null,
      targetPrice: null,
      lastUpdated: "2026-05-20",
      investmentLogic: null,
      catalysts: [],
      operationPlan: null,
    },
  ],

  // ──── 美股 ────
  "us-stocks": [
    {
      id: "lite",
      code: "LITE",
      name: "Lumentum",
      sector: "光通信 / 光源",
      mkt: "us",
      type: "波段",
      color: "#f59e0b",
      reason: "AI 光互连核心标的，EML 激光器 + 硅光技术领先，800G/1.6T 周期受益。",
      strategy: "波段操作，关注云厂商 CapEx 指引和光模块订单。",
      stopLoss: null,
      targetPrice: null,
      lastUpdated: "2026-05-27",
      investmentLogic: {
        oneLiner: "AI 光互连上游稀缺标的，光源/接收器/调制器全栈布局。",
        currentHypothesis: "800G EML 激光器供不应求 + 1.6T 硅光方案客户导入 → 营收加速。",
        coreReason: "LITE 是少数能同时提供 EML（外调制）+ 硅光（集成）方案的光器件公司，AI 互联升级双重受益。",
        status: "波段操作中",
        validUntil: "2026-09",
        questionsToVerify: "云厂商 CapEx 是否持续上修？1.6T 硅光模组何时获得大客户认证？"
      },
      catalysts: [
        {
          catalyst: "下季度营收指引上修",
          timeWindow: "2026年8月（Q4 财报）",
          importance: "高",
          status: "等待中",
          evidence: "营收指引环比增长 > 15%，云厂商光模块订单可见度延长",
          direction: "利好"
        },
      ],
      operationPlan: {
        currentStatus: "波段持仓中",
        buyPlan: "回调至 50 日线附近回补",
        addConditions: "股价缩量回踩支撑位 + 行业催化剂临近",
        reduceConditions: "连续 3 日放量不创新高，减半",
        invalidateConditions: "云厂商 CapEx 指引下修；竞争格局恶化（份额流失）",
        maxPosition: "总仓位的 12%"
      },
    },
    {
      id: "cohr",
      code: "COHR",
      name: "Coherent",
      sector: "光通信 / 激光器",
      mkt: "us",
      type: "监控",
      color: "#6366f1",
      reason: "光通信+材料+激光器多业务平台，AI 数据中心需求催化。",
      strategy: "保持监控，等待合适买点。",
      stopLoss: null,
      targetPrice: null,
      lastUpdated: "2026-05-26",
      investmentLogic: null,
      catalysts: [],
      operationPlan: null,
    },
    {
      id: "aaoi",
      code: "AAOI",
      name: "Applied Optoelectronics",
      sector: "光模块",
      mkt: "us",
      type: "波段",
      color: "#f59e0b",
      reason: "数据中心光模块供应商，受益 AI 集群互联需求。",
      strategy: "波段操作，关注订单公告和客户验证进展。",
      stopLoss: null,
      targetPrice: null,
      lastUpdated: "2026-05-25",
      investmentLogic: null,
      catalysts: [],
      operationPlan: null,
    },
    {
      id: "axti",
      code: "AXTI",
      name: "AXT Inc.",
      sector: "衬底材料",
      mkt: "us",
      type: "监控",
      color: "#6366f1",
      reason: "InP/GaAs 衬底龙头，AI 光模块上游关键材料。",
      strategy: "保持监控，关注衬底认证和出货量。",
      stopLoss: null,
      targetPrice: null,
      lastUpdated: "2026-05-24",
      investmentLogic: null,
      catalysts: [],
      operationPlan: null,
    },
    {
      id: "mrvl",
      code: "MRVL",
      name: "Marvell Technology",
      sector: "数据中心芯片",
      mkt: "us",
      type: "监控",
      color: "#6366f1",
      reason: "数据中心芯片（交换/DPU/PHY），光互连生态链关键节点。",
      strategy: "保持监控，关注定制 ASIC 进展和光模块配套。",
      stopLoss: null,
      targetPrice: null,
      lastUpdated: "2026-05-23",
      investmentLogic: null,
      catalysts: [],
      operationPlan: null,
    },
  ],
};
