// ========================================
// 最近更新数据 — 手动维护，按时间倒序
// ========================================

const updateLog = [
  {
    date: "2026-06-08",
    type: "研报",
    title: "全球AI数据中心产业链国家分工深度研报（PDF整理）",
    stocks: "TSMC / SK Hynix / ASML / NVIDIA / Vertiv / 中际旭创",
    status: "新笔记",
    link: "/articles/global-ai-dc-industry-chain/",
  },
  {
    date: "2026-06-08",
    type: "笔记",
    title: "HBM4重新定价：SemiAnalysis杀的是SOCAMM，不是HBM",
    stocks: "MU / SK hynix / NVDA",
    status: "新笔记",
    link: "/articles/hbm-pricing-repricing/",
  },
  {
    date: "2026-06-07",
    type: "网站维护",
    title: "研究方向页面重构：6张卡片+定位标签+代表标的",
    stocks: "多维",
    status: "已发布",
    link: "/#research",
  },
  {
    date: "2026-06-07",
    type: "网站维护",
    title: "关键验证日历上线+SpaceX IPO条目拆分确认",
    stocks: "SPCX",
    status: "已发布",
    link: "/#calendar",
  },
  {
    date: "2026-06-07",
    type: "网站维护",
    title: "交易环境雷达上线：全球资产收盘分析+下一交易日提示",
    stocks: "多维",
    status: "已发布",
    link: "/",
  },
  {
    date: "2026-06-07",
    type: "持仓同步",
    title: "持仓状态同步：A股东山/航天，美股16只标的改为持有",
    stocks: "NVDA / TSLA / COHR / LITE / GLW / AAOI / AVGO / NOK / HOOD / COIN / 东山精密 / 航天电器",
    status: "已更新",
    link: "/#tracking",
  },
  {
    date: "2026-06-07",
    type: "市场速报",
    title: "全球首座预制化算力中心在青岛落成",
    stocks: "",
    status: "已归档",
    link: "/news/",
  },
  {
    date: "2026-06-07",
    type: "市场速报",
    title: "黄仁勋透露Vera CPU将采用SK海力士DRAM",
    stocks: "NVDA / MU / AMD / INTC",
    status: "已归档",
    link: "/news/",
  },
  {
    date: "2026-06-07",
    type: "市场速报",
    title: "特朗普再向美联储施压，称就业强劲不构成加息理由",
    stocks: "QQQ / SMH",
    status: "已归档",
    link: "/news/",
  },
  {
    date: "2026-06-07",
    type: "市场速报",
    title: "黄仁勋称内存短缺将持续数年",
    stocks: "NVDA / MU / LITE / COHR / AAOI",
    status: "已归档",
    link: "/news/",
  },
  {
    date: "2026-06-07",
    type: "投资框架",
    title: "光通信学习路径：从信号路径到投资价值链",
    stocks: "EML / PD / DSP / FAU / NPO / CPO",
    status: "长期框架",
    link: "/articles/optical-communication-learning-path/",
  },
  {
    date: "2026-06-06",
    type: "标的维护",
    title: "Sivers Semiconductors / POET / VIAV 抽屉页维护",
    stocks: "SIVEF / POET / VIAV",
    status: "继续跟踪",
    link: "/#tracking",
  },
  {
    date: "2026-06-05",
    type: "标的维护",
    title: "NOK / GLW / TSEM 抽屉页维护",
    stocks: "NOK / GLW / TSEM",
    status: "继续跟踪",
    link: "/#tracking",
  },
  {
    date: "2026-06-05",
    type: "市场速报",
    title: "NVIDIA Spectrum-X 以太网硅光技术全面量产，CPO卡点被逐一打破",
    stocks: "NVDA / LITE / COHR / MRVL / AAOI",
    status: "已归档",
    link: "/news/",
  },
  {
    date: "2026-06-05",
    type: "标的维护",
    title: "MRVL / AVGO 抽屉页维护（AI定制芯片+互联核心层）",
    stocks: "MRVL / AVGO",
    status: "继续跟踪",
    link: "/#tracking",
  },
  {
    date: "2026-06-04",
    type: "标的维护",
    title: "AAOI / LITE / COHR / AXTI 抽屉页维护",
    stocks: "AAOI / LITE / COHR / AXTI",
    status: "继续跟踪",
    link: "/#tracking",
  },
  {
    date: "2026-06-04",
    type: "标的维护",
    title: "美湖股份 603319 抽屉页维护（机器人二线弹性）",
    stocks: "603319.SH",
    status: "继续跟踪",
    link: "/#tracking",
  },
  {
    date: "2026-06-04",
    type: "市场速报",
    title: "被动元件涨价扩散：芯片电阻器加入涨价行列",
    stocks: "2327.TW / 000636.SZ / 300408.SZ",
    status: "已归档",
    link: "/news/",
  },
  {
    date: "2026-06-04",
    type: "投资框架",
    title: "Cage：AI互联升级里容易被忽略的小环节",
    stocks: "鼎通 / 奕东",
    status: "长期框架",
    link: "/articles/ai-cage-connector/",
  },
  {
    date: "2026-06-04",
    type: "财报分析",
    title: "AVGO FY2026 Q2财报笔记",
    stocks: "AVGO",
    status: "已归档",
    link: "/articles/avgo-fy2026-q2-earnings/",
  },
  {
    date: "2026-06-04",
    type: "产业研究",
    title: "霍尔木兹海峡通行许可系统开放分析",
    stocks: "原油 / 黄金",
    status: "已归档",
    link: "/articles/hormuz-strait-crisis/",
  },
  {
    date: "2026-06-03",
    type: "标的维护",
    title: "AAOI / LITE / COHR / AXTI / MRVL / AVGO / NOK / GLW / TSEM / Sivers / POET / VIAV 全套抽屉页",
    stocks: "AAOI / LITE / COHR / AXTI / MRVL / AVGO / NOK / GLW / TSEM / SIVEF / POET / VIAV",
    status: "继续跟踪",
    link: "/#tracking",
  },
  {
    date: "2026-06-03",
    type: "产业研究",
    title: "AI光通信23个核心概念全解",
    stocks: "光通信全产业链",
    status: "长期框架",
    link: "/articles/industry-glossary-2026/",
  },
  {
    date: "2026-06-02",
    type: "市场速报",
    title: "六月行情展望：产业约束筛选月",
    stocks: "多维",
    status: "已归档",
    link: "/news/",
  },
  {
    date: "2026-06-01",
    type: "市场速报",
    title: "英伟达台北GTC 2026：AI投资进入建AI工厂阶段",
    stocks: "NVDA / CRWV / LITE / COHR",
    status: "已归档",
    link: "/news/",
  },
];
