// ========================================
// 最近更新数据 — 手动维护，按时间倒序
// ========================================

const updateLog = [
  {
    date: "2026-06-07",
    type: "投资框架",
    title: "光通信学习路径：从信号路径到投资价值链",
    stocks: "EML / PD / DSP / FAU / NPO / CPO",
    status: "长期框架",
    link: "/articles/optical-communication-learning-path/",
  },
  {
    date: "2026-06-06",
    type: "标的维护",
    title: "Sivers Semiconductors / POET / VIAV 抽屉页维护",
    stocks: "SIVEF / POET / VIAV",
    status: "继续跟踪",
    link: "/#tracking",
  },
  {
    date: "2026-06-05",
    type: "标的维护",
    title: "NOK / GLW / TSEM 抽屉页维护",
    stocks: "NOK / GLW / TSEM",
    status: "继续跟踪",
    link: "/#tracking",
  },
  {
    date: "2026-06-05",
    type: "市场速报",
    title: "NVIDIA Spectrum-X 以太网硅光技术全面量产，CPO卡点被逐一打破",
    stocks: "NVDA / LITE / COHR / MRVL / AAOI",
    status: "已归档",
    link: "/news/",
  },
  {
    date: "2026-06-05",
    type: "标的维护",
    title: "MRVL / AVGO 抽屉页维护（AI定制芯片+互联核心层）",
    stocks: "MRVL / AVGO",
    status: "继续跟踪",
    link: "/#tracking",
  },
  {
    date: "2026-06-04",
    type: "标的维护",
    title: "AAOI / LITE / COHR / AXTI 抽屉页维护",
    stocks: "AAOI / LITE / COHR / AXTI",
    status: "继续跟踪",
    link: "/#tracking",
  },
  {
    date: "2026-06-04",
    type: "标的维护",
    title: "美湖股份 603319 抽屉页维护（机器人二线弹性）",
    stocks: "603319.SH",
    status: "继续跟踪",
    link: "/#tracking",
  },
  {
    date: "2026-06-04",
    type: "市场速报",
    title: "被动元件涨价扩散：芯片电阻器加入涨价行列",
    stocks: "2327.TW / 000636.SZ / 300408.SZ",
    status: "已归档",
    link: "/news/",
  },
  {
    date: "2026-06-04",
    type: "投资框架",
    title: "Cage：AI互联升级里容易被忽略的小环节",
    stocks: "鼎通 / 奕东",
    status: "长期框架",
    link: "/articles/ai-cage-connector/",
  },
  {
    date: "2026-06-04",
    type: "财报分析",
    title: "AVGO FY2026 Q2财报笔记",
    stocks: "AVGO",
    status: "已归档",
    link: "/articles/avgo-fy2026-q2-earnings/",
  },
  {
    date: "2026-06-04",
    type: "产业研究",
    title: "霍尔木兹海峡通行许可系统开放分析",
    stocks: "原油 / 黄金",
    status: "已归档",
    link: "/articles/hormuz-strait-crisis/",
  },
  {
    date: "2026-06-03",
    type: "标的维护",
    title: "AAOI / LITE / COHR / AXTI / MRVL / AVGO / NOK / GLW / TSEM / Sivers / POET / VIAV 全套抽屉页",
    stocks: "AAOI / LITE / COHR / AXTI / MRVL / AVGO / NOK / GLW / TSEM / SIVEF / POET / VIAV",
    status: "继续跟踪",
    link: "/#tracking",
  },
  {
    date: "2026-06-03",
    type: "产业研究",
    title: "AI光通信23个核心概念全解",
    stocks: "光通信全产业链",
    status: "长期框架",
    link: "/articles/industry-glossary-2026/",
  },
  {
    date: "2026-06-02",
    type: "市场速报",
    title: "六月行情展望：产业约束筛选月",
    stocks: "多维",
    status: "已归档",
    link: "/news/",
  },
  {
    date: "2026-06-01",
    type: "市场速报",
    title: "英伟达台北GTC 2026：AI投资进入建AI工厂阶段",
    stocks: "NVDA / CRWV / LITE / COHR",
    status: "已归档",
    link: "/news/",
  },
];
