const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),vm=require('node:vm');
const {JSDOM}=require('jsdom');const root=path.resolve(__dirname,'..');
const context={};vm.createContext(context);vm.runInContext(fs.readFileSync(path.join(root,'js/articles.js'),'utf8')+';this.articles=articles;',context);const articles=context.articles;
const archive=JSON.parse(fs.readFileSync(path.join(root,'content/archives.json')));let checks=0;
function test(name,fn){fn();checks++;console.log('PASS',name);}
function load(route,stored){const pathname=route.split('?')[0];const html=fs.readFileSync(path.join(root,pathname,'index.html'),'utf8');const dom=new JSDOM(html,{url:'http://localhost:8092'+route,runScripts:'outside-only',pretendToBeVisual:true});if(stored)dom.window.localStorage.setItem('xxyalpha.research-notebook.v1',stored);const scripts=['articles','calendar-data','archive-data','journal'].map(x=>fs.readFileSync(path.join(root,'js/'+x+'.js'),'utf8')).join('\n');dom.window.eval(scripts);return dom;}
function fire(dom,selector,type){dom.window.document.querySelector(selector).dispatchEvent(new dom.window.Event(type,{bubbles:true,cancelable:true}));}
function text(dom){return dom.window.document.body.textContent;}
const allRoutes=['/','/notes/','/events/','/research/','/learning/','/calendar/','/workbench/',...archive.events.map(e=>'/events/'+e.id+'/'),...archive.companies.map(c=>'/research/'+c.id.toLowerCase()+'/'),...archive.hypotheses.map(h=>'/learning/'+h.id+'/'),...articles.map(a=>a.file)];
for(const route of allRoutes)test('Render and internal links '+route,()=>{const dom=load(route);assert.ok(dom.window.document.querySelector('h1'));for(const el of dom.window.document.querySelectorAll('a[href],script[src],link[href]')){const attr=el.getAttribute('href')||el.getAttribute('src');if(!attr||attr.startsWith('#')||!attr.startsWith('/'))continue;const clean=decodeURIComponent(attr.split(/[?#]/)[0]);assert.ok(fs.existsSync(path.join(root,clean)),route+' broken '+attr);}dom.window.close();});
test('45 original article bodies preserved',()=>{const cp=require('node:child_process');for(const a of articles){const old=cp.execFileSync('git',['show','HEAD:'+a.file.slice(1)+'index.html'],{cwd:root,encoding:'utf8'});const current=fs.readFileSync(path.join(root,a.file,'index.html'),'utf8');const body=s=>s.match(/<main\b[^>]*>([\s\S]*?)<\/main>/)[1];assert.equal(body(current),body(old),a.id);}});
test('Article metadata and public registry are unchanged',()=>{const cp=require('node:child_process');for(const f of ['js/articles.js','content/articles.json','js/calendar-data.js'])assert.equal(fs.readFileSync(path.join(root,f),'utf8'),cp.execFileSync('git',['show','HEAD:'+f],{cwd:root,encoding:'utf8'}));});
test('Search, type filter, sort and no-results state',()=>{const d=load('/notes/?q=MU'),doc=d.window.document;assert.ok(doc.querySelectorAll('.article-row').length>0);doc.querySelector('#article-type').value='财报分析';fire(d,'#article-type','change');for(const row of doc.querySelectorAll('.article-row'))assert.equal(row.querySelector('.type-label').textContent,'财报分析');doc.querySelector('#article-sort').value='asc';fire(d,'#article-sort','change');const dates=[...doc.querySelectorAll('.date')].map(e=>e.dateTime);assert.deepEqual(dates,[...dates].sort());doc.querySelector('#article-search').value='<img src=x onerror=alert(1)>';fire(d,'#article-search','input');assert.equal(doc.querySelectorAll('.article-row').length,0);assert.ok(doc.querySelector('.empty'));assert.equal(doc.querySelectorAll('img[src=x]').length,0);d.window.close();});
test('Sequential reading hides later article summaries and sidebar hindsight',()=>{const d=load('/events/memory-earnings-2026/'),doc=d.window.document;assert.equal(doc.querySelectorAll('.timeline-row').length,6);fire(d,'[data-mode=sequence]','click');assert.equal(doc.querySelectorAll('.timeline-row').length,1);assert.ok(!doc.querySelector('#event-timeline').textContent.includes('存储鬼故事'));assert.ok(!doc.querySelector('#event-sidebar').textContent.includes('关联的经验'));assert.ok(doc.querySelector('#previous-record').disabled);fire(d,'#next-record','click');assert.equal(doc.querySelectorAll('.timeline-row').length,2);fire(d,'#previous-record','click');assert.equal(doc.querySelectorAll('.timeline-row').length,1);d.window.close();});
test('Company research includes financial-report tags and switches categories',()=>{const d=load('/research/mu/');assert.ok(text(d).includes('机构投资者视角拆解'));fire(d,'[data-company-mode=question]','click');assert.ok(d.window.document.querySelector('#company-articles h2'));d.window.close();const empty=load('/research/tsla/');assert.ok(empty.window.document.querySelector('.empty'));empty.window.close();});
test('Calendar defaults to current month, history is explicitly unverified',()=>{const d=load('/calendar/');assert.ok(d.window.document.querySelector('.empty'));fire(d,'#calendar-history','click');assert.ok(d.window.document.querySelectorAll('.calendar-row').length>0);assert.ok(text(d).includes('历史日程 · 结果待补'));fire(d,'#calendar-current','click');assert.equal(d.window.document.querySelectorAll('.calendar-row').length,0);d.window.close();});
test('Notebook saves, survives reload, escapes markup and appends revisions',()=>{const d=load('/workbench/?company=MU&event=memory-earnings-2026'),doc=d.window.document;assert.equal(doc.querySelector('#note-company').value,'MU');doc.querySelector('[name=title]').value='<img src=x onerror=alert(1)>';doc.querySelector('[name=observed]').value='Test observation';fire(d,'#note-form','submit');const raw=d.window.localStorage.getItem('xxyalpha.research-notebook.v1'),first=JSON.parse(raw)[0];assert.equal(first.company,'MU');assert.equal(first.event,'memory-earnings-2026');assert.ok(first.createdAt);assert.equal(doc.querySelectorAll('img[src=x]').length,0);doc.querySelector('[name=title]').value='修订';doc.querySelector('[name=observed]').value='New evidence';doc.querySelector('[name=revises]').value=first.id;fire(d,'#note-form','submit');const saved=d.window.localStorage.getItem('xxyalpha.research-notebook.v1');assert.deepEqual(JSON.parse(saved)[0],first);assert.equal(JSON.parse(saved)[1].revises,first.id);const next=load('/workbench/',saved);assert.equal(next.window.document.querySelectorAll('.draft-card').length,2);next.window.close();d.window.close();});
test('Corrupt storage never gets silently overwritten',()=>{const d=load('/workbench/','{bad');assert.ok(text(d).includes('暂停保存'));d.window.document.querySelector('[name=title]').value='test';d.window.document.querySelector('[name=observed]').value='data';fire(d,'#note-form','submit');assert.equal(d.window.localStorage.getItem('xxyalpha.research-notebook.v1'),'{bad');d.window.close();});
test('Mobile navigation toggle exposes expanded state',()=>{const d=load('/');fire(d,'.mobile-menu','click');assert.equal(d.window.document.querySelector('.mobile-menu').getAttribute('aria-expanded'),'true');assert.ok(d.window.document.querySelector('.primary-nav.open'));d.window.close();});

async function asyncTests(){
const d=load('/workbench/'),doc=d.window.document;doc.querySelector('[name=title]').value='Backup test';doc.querySelector('[name=observed]').value='Evidence';fire(d,'#note-form','submit');const before=d.window.localStorage.getItem('xxyalpha.research-notebook.v1'), note=JSON.parse(before)[0];
let exported;d.window.URL.createObjectURL=blob=>{exported=blob;return 'blob:local-test';};d.window.URL.revokeObjectURL=()=>{};d.window.HTMLAnchorElement.prototype.click=function(){};fire(d,'#export-notes','click');assert.ok(exported);const exportedText=await new Promise((resolve,reject)=>{const reader=new d.window.FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsText(exported);});assert.deepEqual(JSON.parse(exportedText).notes,JSON.parse(before));checks++;console.log('PASS Export contains exact saved draft records');
async function restore(obj){Object.defineProperty(doc.querySelector('#import-notes'),'files',{value:[{size:100,text:async()=>JSON.stringify(obj)}],configurable:true});fire(d,'#import-notes','change');await new Promise(r=>setImmediate(r));}
await restore({version:1,notes:[note]});assert.equal(JSON.parse(d.window.localStorage.getItem('xxyalpha.research-notebook.v1')).length,1);checks++;console.log('PASS Import deduplicates an existing backup');
const newNote={...note,id:'restored-new',title:'Restored record'};await restore({version:1,notes:[newNote]});assert.equal(JSON.parse(d.window.localStorage.getItem('xxyalpha.research-notebook.v1')).length,2);const stored=d.window.localStorage.getItem('xxyalpha.research-notebook.v1');await restore({version:1,notes:[{...note,title:'Conflicting rewrite'}]});assert.equal(d.window.localStorage.getItem('xxyalpha.research-notebook.v1'),stored);checks++;console.log('PASS Valid restore merges records; conflicting IDs cannot overwrite originals');
await restore({version:1,notes:[{id:'malformed'}]});assert.equal(d.window.localStorage.getItem('xxyalpha.research-notebook.v1'),stored);checks++;console.log('PASS Malformed backup preserves all existing notes');d.window.close();
for(const e of archive.events)for(const id of e.articleIds)assert.ok(articles.find(a=>a.id===id));for(const h of archive.hypotheses){for(const id of h.articleIds)assert.ok(articles.find(a=>a.id===id));for(const id of h.eventIds)assert.ok(archive.events.find(e=>e.id===id));}checks++;console.log('PASS Archive references resolve to existing records');
console.log(`Completed ${checks} checks. DOM tests only; no visual browser validation.`);
}
asyncTests().catch(e=>{console.error(e);process.exitCode=1;});
